### ISSUE TITLE
CSS conflict with bokeh in conversion to slides?

### ISSUE THREAD

**Issue by sggaffney** [jupyter/nbconvert#29] opened 2015-06-04 00:21 UTC
When my nbconvert slides include a Bokeh plot, I get unwanted borders around the `<td>`, `<tr>` and `<table>` elements of the plot, inheriting from `.rendered_html`. The appearance of the dropdown for crosshair/hover is also affected (forced 'on').

![screen shot 2015-06-03 at 14 10 37](https://cloud.githubusercontent.com/assets/5185412/7974198/d03adbce-0a2c-11e5-84ac-07710886b9fa.png)

Jupytr 3.1.0
Reveal.js 2.6.2
Bokeh 0.9.0

**Comment by damianavila** [comment] 2015-06-10 00:00
Probably a conflict between reveal js <> bokeh js <> jupyter js... ehh, a lot of js out there, I will take a look and investigate. Thanks for the report.

**Comment by damianavila** [comment] 2015-07-20 03:51
The borders are easy... you can put the following in a custom css and you are done:

```css
.rendered_html table, .rendered_html td, .rendered_html th, .rendered_html tr {
  border: none;
}
```

But the dropdown is more difficult because it is caused by `reveal.css` setting `display: inline-block` and it does not seems to be any other value working... and unless somebody knows how to "delete" a css rule (I think you can't do it), a really weird workaround is to fix the reveal.css file itself... grrr... I hate when this happens... 

Any other suggestions are welcomed...

**Comment by hongyoon** [comment] 2015-11-20 00:41
@damianavila I have a similar issue as well. The hover tool does not display info when converted to slides.

**Comment by damianavila** [comment] 2017-05-31 20:45
Tested with latest nbconvert 5.2.1 and latest Bokeh 0.12.5 and I can see the plot without borders.
Closing now.

**Closed by damianavila** 2017-05-31 20:45 UTC
Labels: slides
