### ISSUE TITLE
AttributeError in MathBlockParser

### ISSUE THREAD

**Issue by kobina-adu** [jupyter/nbconvert#2201] opened 2024-12-31 17:00 UTC
I encountered an **AttributeError** when exporting my .ipynb to .html. The process involved running **jupyter-nbconvert** and due to a typo in the **MathBlockParser** class from the **mistune** package. The error message indicated that there is no attribute **parse_axt_heading**, and it suggested that it might be a typo for parsing **parse_atx_heading**.

Traceback:
AttributeError: 'MathBlockParser' object has no attribute 'parse_axt_heading'. Did you mean: 'parse_atx_heading'?

Steps to Reproduce:
1. Install the latest version of jupyter (it comes along with the nbconvert and mistune packages).
2. export your single notebook to an html file or run the jupyter-nbconvert on a jupyter notebook.

Temporal fix:
To resolve the issue temporarily, I duplicated the **parse_atx_heading** method in the **MathBlockParser** class and named the duplicate **parse_axt_heading**. Changing the name of the attribute affected other operations hence the duplication served right.

Environment:
Python version: 3.13
nbconvert version: [version]
mistune version: [version]
Operating system: Windows 10

Additional Information: Please let me know if you need any further information or if there is a better way to address this issue.

**Comment by bollwyvl** [comment] 2024-12-31 17:51
Dupe of #2198

**Closed by bollwyvl** 2024-12-31 17:51 UTC
