### ISSUE TITLE
How to save widget state after executing notebook

### ISSUE THREAD

**Issue by oscar6echo** [jupyter/nbconvert#751] opened 2018-02-05 09:23 UTC
I automate the execution and conversion to html of notebooks with this convenience package [notebook-snapshot](https://github.com/oscar6echo/notebook-snapshot). In particular the execution script is [there](https://github.com/oscar6echo/notebook-snapshot/blob/master/notebook_snapshot/execute.py) straight from the documentation.  

My notebooks contain widgets. So I need to 'save widget state' after execution.  
If I run a notebook manually, I would use click on 'Clear widget state' then 'Save widget state' to embed only the latest state in the notebook. 

How to do that from nbconvert ?

**Comment by scottdraves** [comment] 2018-02-26 14:45
We would like to develop a fix for this.  Any special guidance from the maintainers?

**Comment by jasongrout** [comment] 2018-03-19 20:16
> We would like to develop a fix for this. Any special guidance from the maintainers?

It looks like you are already working on it, from the referenced commits above. Thanks! How is it going? Any sticky points?

**Comment by scottdraves** [comment] 2018-03-19 20:40
https://github.com/jupyter/nbconvert/pull/779
there's a problem with python2.7 and unicode that we should have resolved tomorrow.
actually have several PRs that could use attention....

**Comment by mpacer** [comment] 2018-03-19 20:45
Could you list those PRs?

**Comment by scottdraves** [comment] 2018-03-19 20:46
https://github.com/jupyter/nbconvert/pull/778
https://github.com/jupyter/nbconvert/pull/779
https://github.com/jupyter/nbconvert/pull/780

**Comment by kennmyers** [comment] 2018-07-31 23:50
Hey, what's the state of this?  I'm very interested in this feature because I convert a lot of notebooks to html via cmd line and was hoping to include my widgets in those conversions and I think this is a feature I've been looking for.

**Comment by Juanlu001** [comment] 2019-01-07 17:30
Latest PR addressing this issue: https://github.com/jupyter/nbconvert/pull/900

**Comment by akhmerov** [comment] 2019-08-08 13:17
I believe this was closed in 5.5, see [here](https://github.com/jupyter/nbconvert/blob/master/docs/source/changelog.rst#ipywidget-support).

**Comment by Juanlu001** [comment] 2019-08-08 13:22
Indeed, however with the new widgets functionality present in nbconvert 5.5, I am trying to convert a very simple notebook containing a slider to slides like this:

```
$ jupyter nbconvert --execute Untitled.ipynb --ExecutePreprocessor.store_widget_state=True --to slides
```

However, when I see them the widget is not shown. Perhaps I did not understand the feature?

**Comment by akhmerov** [comment] 2019-08-08 14:05
This might be an unrelated issue, about embedding notebook javascript in the slides template; do you see the widgets if you convert to html?

**Comment by Juanlu001** [comment] 2019-08-08 16:51
Sorry, lazy comment - I will open a new issue with a notebook to reproduce and some screenshots.

**Comment by akhmerov** [comment] 2019-08-15 09:04
@maartenbreddels, should this issue be closed? (I believe you're one of the devs that are up to date on its status, my apologies if it isn't the case.)

**Comment by maartenbreddels** [comment] 2019-08-15 10:40
Indeed, this can be closed.

**Closed** 2019-08-15 14:22 UTC
Labels: Preprocessor:Execute

**Comment by Juanlu001** [comment] 2019-10-26 13:12
Regarding my last comment, this issue has already been reported at https://github.com/jupyter/nbconvert/issues/1097.
