### ISSUE TITLE
Slides failing to render correctly

### ISSUE THREAD

**Issue by damontallen** [jupyter/nbconvert#157] opened 2015-11-16 02:15 UTC
This seems like a problem that showed up before but I can't seem to find it right now.  I just did a pip update and now when I use nbconvert to create slides for github.io all I see is a partially rendered first slide and no navigation arrows.  When I used --post serve I was able to get the slide show to play beyond the first slide but could not scroll down to review all the content of longer slides.  I was able to fix my current problem by doing a diff against a working older version of a different show but this is going to be a long term problem.

[Working version](http://damontallen.github.io/Construction-materials/Paint.slides.html) 
[Failing version](http://damontallen.github.io/Construction-materials/Paint_fail.slides.html)

[Original Notebook](https://github.com/damontallen/Construction-materials/blob/master/Plastic.ipynb)

**Comment by damianavila** [comment] 2015-11-16 12:02
Thanks for the report, I will explore it...

**Comment by damontallen** [comment] 2015-11-23 17:41
I ran an update prior to converting this week and had to manually fix the current slideshow again.  I created a [diff file](https://github.com/damontallen/Construction-materials/blob/master/Slideshow_problems/Glass.diff) showing the working show ([Glass.slides.html](http://damontallen.github.io/Construction-materials/Glass.slides.html)) in red and default version in green ([Glass-1.slides.html](http://damontallen.github.io/Construction-materials/Glass-1.slides.html)).  I don't know enough about everything that's going on to be able to spot the problem but hopefully this additional data will help you.

**Comment by takluyver** [comment] 2015-12-02 16:09
@damianavila have you got anywhere with this?

**Comment by damianavila** [comment] 2015-12-02 17:33
In my todo list... I will further investigate at tonight...

**Comment by damianavila** [comment] 2017-05-31 21:09
>I just did a pip update and now when I use nbconvert to create slides for github.io all I see is a partially rendered first slide and no navigation arrows.

Do you have an accompanying `reveal.js`, right? If you are not using `--post serve` you need to provide a local `reveal.js` and serve it along with you slides.  

>When I used --post serve I was able to get the slide show to play beyond the first slide but could not scroll down to review all the content of longer slides

I am able to reproduce the scrolling issue... and I am proposing a solution in PR #600.

**Comment by damianavila** [comment] 2017-05-31 21:30
> Do you have an accompanying reveal.js, right? If you are not using --post serve you need to provide a local reveal.js and serve it along with you slides.

Alternative, if you don't want to use/ship a local reveal you can just point the reveal-prefix to some reveal.js out there, for instance:
```
jupyter nbconvert damon_slide.ipynb --to slides --reveal-prefix "https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.1.0"
```
Will load correctly when you serve it. And, probably, it will load most of you stuff if you try to open it with the browser (it could be some issues with videos or images, I guess... this is why we recommend to serve them or use `--post serve`).

**Comment by damontallen** [comment] 2017-06-01 13:26
I do have the accompanying reveal.js.


Regards,
Damon

Damon T. Allen Ph.D.
Adjunct Professor
(352) 234-3266
damontallen@gmail.com
340 Rinker Hall
School of Construction Management
University of Florida

**Comment by damontallen** [comment] 2017-06-01 13:31
This was my latest attempt to update everything. [https://damontallen.github.io/temporary-structures/Week%200%20-%20Greetings.slides.html#/](https://damontallen.github.io/temporary-structures/Week%200%20-%20Greetings.slides.html#/).  If you scroll down on that first slide you can see more content, briefly.

**Comment by damianavila** [comment] 2017-06-01 16:40
> If you scroll down on that first slide you can see more content, briefly.

Yep, I replicated that issue and a working PR to fix the behavior lives in #600 (along with some enhancement on the scrolling situation).

**Comment by damianavila** [comment] 2017-06-07 13:34
@damontallen #600 was merged, so if you try from master, you should be able to have scrolling slides with the the option `--SlidesExporter.reveal_scroll=True` (now the scrolling feature is, by default, False).

I will close this now, but free to reopen if you still see the issue.

**Closed by damianavila** 2017-06-07 13:34 UTC
Labels: slides

**Comment by damontallen** [comment] 2017-06-18 19:01
@damianavila Thank you, but it only works part of the time.  I did a fresh install of Jupyter and IPython in a new virtualenv and then install nbconvert via a clone of master.  On this [first slide](https://damontallen.github.io/temporary-structures/Week%200%20-%20Greetings.slides.html) the scroll bar didn't show up until after I went to the slide below and came back.  This [later slide](https://damontallen.github.io/temporary-structures/Week%200%20-%20Greetings.slides.html#/1/6) never showed the scroll bar at all.

**Comment by damianavila** [comment] 2017-06-19 13:13
> I did a fresh install of Jupyter and IPython in a new virtualenv and then install nbconvert via a clone of master. On this first slide the scroll bar didn't show up until after I went to the slide below and came back. This later slide never showed the scroll bar at all.

OK, that is weird... I can check what you see in the first slide... for the `later slide`, I can see the scroll when I go to other slide and come back... this seems related with a missing calculation at the time to start the slideshow maybe? I will investigate because I did not see that in my tests... but maybe you can help me a little bit, can you try adding this piece of code in the resulting slides.html and check if the behavior improves?
Note I put a bigger piece of code as context, but you only need to add one line of code according to the instructions in the code block.

```
        function setScrollingSlide() {
            var scroll = {{ resources.reveal.scroll | json_dumps }}
            if (scroll === true) {
              var h = $('.reveal').height() * 0.95;
              $('section.present').find('section')
                .filter(function() {
                  return $(this).height() > h;
                })
                .css('height', 'calc(95vh)')
                .css('overflow-y', 'scroll')
                .css('margin-top', '20px');
            }
        }

        // This is the line you need to add Damon
        Reveal.addEventListener('ready', setScrollingSlide);

        // check and set the scrolling slide every time the slide change
        Reveal.addEventListener('slidechanged', setScrollingSlide);

```
Thanks in advance.

**Comment by damontallen** [comment] 2017-06-19 14:57
@damianavila Adding the additional event listener did help with the first slide but I still can't see a scroll bar on the other slide.  [This slide](https://damontallen.github.io/temporary-structures/Week%200%20-%20Greetings.slides.html#/3) is probably a better test case slide from the same lecture for other issue.  I was never able to make a scroll bar appear in Firefox, Chromium or Chrome.  The slide to the left has a scroll bar (as it should) so I'm not seeing the pattern.  If you can see it, let me know the browser you are using.

**Comment by damianavila** [comment] 2017-06-19 19:40
> Adding the additional event listener did help with the first slide

Good to know!!

> This slide is probably a better test case slide from the same lecture for other issue. I was never able to make a scroll bar appear in Firefox, Chromium or Chrome

I am actually seeing that scroll bar in the slide you linked. My browser: Version 58.0.3029.110 Built on Ubuntu , running on Ubuntu 16.04 (64-bit).

**Comment by damontallen** [comment] 2017-06-19 20:36
I  have the same build but I'm running Ubuntu 17.04 (64-bit).  I did a fresh install of Ubuntu on April 14th.

**Comment by damianavila** [comment] 2017-06-20 10:15
OK, I guess we need to keep looking into this. I will reinstall Ubuntu soon to be 17.04, then I can try to reproduce what you are seeing... sorry to not be more helpful.

**Comment by damontallen** [comment] 2017-06-20 23:52
@damianavila No problem.  I'm glad you are looking into it for me.  I've just been reusing the old HTML code for years.  It will be nice to finally get to use slides without having to do a manual merge.

**Comment by sobayed** [comment] 2018-08-22 06:48
Any updates on this? I'm facing the same issue right now and the test slide provided by @damontallen is cut off without a scrollbar for me, too (Chrome 68.0.3440, Windows 10 64 bit).

**Comment by Serfentum** [comment] 2018-11-21 21:50
Looks like I have same issue

**Comment by JeroenSchmidt** [comment] 2019-10-30 12:47
Any updates on this? My slides still end prematurely when scrolling through a large cell.
I am running `ubuntu 18.03` and `nbconvert 5.6.0`

**Comment by MSeal** [comment] 2019-11-01 04:46
I don't think anyone is actively looking at this issue. There's another open issue which is probably the same one: https://github.com/jupyter/nbconvert/issues/1097#issuecomment-546601649. I'll mark it as help-wanted as I don't have time atm to look into it. If someone could narrow down what parts of the template are generating outputs that conflict or are missing, it'd help make solving the problem easier.
