### ISSUE TITLE
Output widgets do not render in the correct places

### ISSUE THREAD

**Issue by eric-wieser** [jupyter/nbconvert#1199] opened 2020-02-24 16:56 UTC
`ipywidgets.Output` objects seem to be emitted at the top level, not in their appropriate container.

A simple example is:

```python
import ipywidgets

vals = [1, 2, 3]
outputs = [
    ipywidgets.Output(layout=ipywidgets.Layout(flex='1'))
    for i in range(vals)
]
grid = ipywidgets.HBox(outputs)
for output, val in zip(outputs, vals):
    with output:
        print("val = {}".format(val))
grid
```

Filing after discovering this stackoverflow question: https://stackoverflow.com/questions/57285733

**Nbconvert version:** 5.6.1

**Comment by MSeal** [comment] 2020-02-24 17:44
Yes this is a known issue, ipywidget Outputs assume there is a widget driver (usually front-end) managing their state.

Closing the issue as it's a duplicate of #923 and has been forwarded to https://github.com/jupyter/nbclient/issues/24 where the issue will be fixed

**Closed by MSeal** 2020-02-24 17:44 UTC

**Comment by eric-wieser** [comment] 2020-02-24 17:49
Thanks for the quick response.

In the meantime, is there an easy way for me to insert an `Ipython.display.Javascript` object into a container? Or would I have to make my object a widget too?

**Comment by MSeal** [comment] 2020-02-24 18:12
So if you call

```
from  IPython.display import Javascript                                                                                                                                              

display(Javascript(my_js_script_here), 
    include=['application/javascript'] 
)   
```

It will save the javascript snippet for the notebook to reuse, but it won't execute anything in javascript because nbconvert is executing in headless mode with no browser present. What this means is that when the notebook is loaded it will try to inject the javascript. At first this won't work for security reasons but there is an option under File -> Trust this Notebook which will turn on the notebook javascript you generated when loaded in Jupyter Classic.
