### ISSUE TITLE
Is nbconvert expected to comment out magic commands?

### ISSUE THREAD

**Issue by elmerehbi** [jupyter/nbconvert#651] opened 2017-08-21 13:57 UTC
Should I expect nbconvert to comment out magic commands?

**Comment by Skitionek** [comment] 2020-03-17 14:20
My workaround I wish I had have found in here earlier: https://github.com/jupyter/nbconvert/issues/503#issuecomment-600095120

**Comment by t-makaro** [comment] 2020-08-14 21:42
I'm going to close this as a duplicate of #503. We are aware of this annoyance.

**Closed by t-makaro** 2020-08-14 21:42 UTC
Labels: duplicate, format:Script
