### ISSUE TITLE
Honor cell skipping metadata in PDF

### ISSUE THREAD

**Issue by flying-sheep** [jupyter/nbconvert#146] opened 2015-10-27 10:15 UTC
hi, i often have some setup code in a first cell that is only technical or aesthetic. e.g. the following line is needed to convert IRkernel notebooks to PDF without having inkscape convert all the SVGs to PDF beforehand:

```r
options(jupyter.plot_mimetypes = c('image/png', 'image/svg+xml', 'application/pdf'))
```

currently i need to create this template:

```python
((*- extends 'article.tplx' -*))

((*- block any_cell -*))
((*- if cell['metadata'].get('slideshow', {}).get('slide_type', '') != 'skip' -*))
((( super() )))
((*- endif -*))
((*- endblock any_cell -*))
```

and then call `jupyter nbconvert --to=pdf --template=skip.tplx notebook.ipynb` instead of using the GUI

**Comment by minrk** [comment] 2015-10-27 12:26
Since the PDF export isn't a slideshow, it doesn't make sense for the output to be affected by the slideshow metadata. A custom template as you have shown for PDF slideshows does make sense, but not in the PDF or LaTeX exports that we have currently.

**Comment by flying-sheep** [comment] 2015-10-27 12:59
sure, but it’s the closest thing we have.

### from a practical standpoint:

1. people using this for teaching *right now* need to skip cells.
2. how to allow them to skip cells without using templates (they are overkill and less convenient to use than the notebook browser UI)?

### from a perfectionist standpoint:

* do we want to create cell metadata toolbars for all kinds of output formats? we’d have to agree on which is which. is latex/pdf/markdown/html some sort of “document” output format type?
* or should we expose generic things that apply to all output formats (like e.g. skipping cells) that should be available in some way?

**Comment by minrk** [comment] 2015-10-27 13:11
We are planning to use a tagging system that would allow specifying things like 'hide input' and a general 'skip', which would be a more generic way of adding marks that can be used in various contexts. Hardcoding treatment of deliberately slide-specific metadata to non-slide output would not be appropriate in the *default* templates. It is in fact the deliberate intent of the slide metadata to allow hiding these things from slide output and *not* other output, so it would be quite frustrating to some to change that behavior. If you are using it *right now*, then *right now* you can do it with the example you have already provided.

**Comment by flying-sheep** [comment] 2015-10-27 18:39
i’m not using that right now, but people i work with do :smile:

**Comment by takluyver** [comment] 2015-12-02 16:07
Cell tagging is tracked in jupyter/notebook#601.

I'm closing this issue because the behaviour in question is as intended.

**Closed by takluyver** 2015-12-02 16:07 UTC
