### ISSUE TITLE
Markdown with backslashes causes PDF exports to fail

### ISSUE THREAD

**Issue by kycutler** [jupyter/nbconvert#1459] opened 2020-10-27 19:49 UTC
### Description
When exporting a notebook to PDF via LaTeX, backslashes inside of markdown cells can cause LaTex "Undefined control sequence" errors.

### Steps to Reproduce
[notebook.txt](https://github.com/jupyter/nbconvert/files/5447737/notebook.txt)
1. Create a notebook with a markdown cell
2. Add some text to that markdown cell containing a backslash, e.g. `\n`, `C:\Users\...`, etc.
3. Export to PDF via LaTeX
4. Observe failure due to `Undefined control sequence` LaTeX error

**Nbconvert version: 5.5.0, 6.0.7**

**Comment by t-makaro** [comment] 2020-10-28 00:47
You can use a double backslash in markdown. It renders the same in Jupyter, and it works fine in the PDF exporter. This is not a simple error to solve in general since equations use backslashes.

**Comment by t-makaro** [comment] 2020-10-28 00:52
Closing as duplicate of #736

**Closed by t-makaro** 2020-10-28 00:52 UTC
