### ISSUE TITLE
Cannot export to PDF with images in notebooks

### ISSUE THREAD

**Issue by whositwhatnow** [jupyter/nbconvert#1326] opened 2020-07-16 11:56 UTC
Running into issues when I got to export to PDF using latex.  Jupyterhub 1.1.0, notebook 6.0.3, nbconvert 5.6.1

The images are being dragged and dropped into a markdown cell:

`![grass.jpg](attachment:grass.jpg)`

Image gets inserted no problem, I am able to see the image in the note in print preview, but when I go to export to PDF in my Jupyternotebook it fails

`! Unable to load picture or PDF file 'attachment:grass.jpg'.
<to be read again> 
                   }
l.391 \includegraphics{attachment:grass.jpg}`

When i try the same via CLI i get the same message.

**Comment by t-makaro** [comment] 2020-07-20 06:34
This is a known problem with attachments. If you use a file path, then it will work.

I'm closing this as a duplicate of #1079. Please add any information there.

**Closed by t-makaro** 2020-07-20 06:34 UTC

**Comment by mgeier** [comment] 2020-07-20 09:06
Until this is fixed in `nbconvert`, you could use Sphinx and my extension https://nbsphinx.readthedocs.io/ to create a PDF.

`nbsphinx` supports attachments, but TBH I've never tried it with JPG images (only with PNG).

**Comment by tashrifbillah** [comment] 2022-01-13 20:48
Hi @t-makaro , I have this in my notebook:

```<img src="artifacts/motion.png" width="400" height="400"/>```

Instead, what *file path* should I use?

**Comment by Plinsboorg** [comment] 2022-01-22 11:39
> Instead, what _file path_ should I use?

Hello, @tashrifbillah 
I created a demo notebook for you. 

![изображение](https://user-images.githubusercontent.com/42300339/150636884-7414986f-bf0c-471d-85b4-4178360ce04d.png)

In my case this command ``` ![Alternative_text](artifacts/Picture.jpg) ```  works fine in PDF export. 
But this command ```<img src="artifacts/Picture.jpg" width="400" height="400"/>``` is not displaying anything in PDF. 

![изображение](https://user-images.githubusercontent.com/42300339/150636895-b5d0890e-4edd-47ce-8bd8-db16c0e65131.png)

Pay attention that 
1. I use slash (artifacts/Picture.jpg) in my path because I use Windows. In the case of Linux backslash is needed.
2. I use PDF export via Latex (not webPDF)

**Comment by tashrifbillah** [comment] 2022-01-24 01:21
Denis (@Plinsboorg), thank you for your time. Contrary to your `#2`, I use:

>  jupyter-nbconvert --to pdfviahtml my.ipynb

Is that my problem then? If yes, could you suggest what option from here to use?

```
$ jupyter-nbconvert --help
...
...
--to=<Unicode> (NbConvertApp.export_format)
    Default: 'html'
    The export format to be used, either one of the built-in formats
    ['PDFviaHTML', 'asciidoc', 'custom', 'html', 'latex', 'markdown',
    'notebook', 'pdf', 'pdfviahtml', 'python', 'rst', 'script', 'slides'] or a
    dotted object name that represents the import path for an `Exporter` class
...
...
```
By the way, I already posted my solution [here](https://github.com/jupyter/nbconvert/issues/1079#issuecomment-1012601618).
