### ISSUE TITLE
Built-in Reveal.js themes seem to incorrectly display background

### ISSUE THREAD

**Issue by cadojo** [jupyter/nbconvert#1250] opened 2020-05-05 20:40 UTC
When using many of the built-in reveal.js slide themes (black.css, solarized.css, moon.css), the background of the presentation stays white. Strangely, using sky.css correctly displays a colored background.

I am using MacOS Catalina 10.15.4. This problem occurs in Safari, Firefox, and Chrome.

Below is the HTML tags that I'm using to load the theme. The file is generated from a Jupyter notebook using `jupyter nbconvert file.ipynb --to slides --SlidesExporter.reveal_theme=moon`. I hope I am not missing something - I looked elsewhere in the slides.html file, and didn't see any obvious place where the background color was being overwritten.

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>

<!-- General and theme style sheets -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.5.0/css/reveal.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.5.0/css/theme/solarized.css" id="theme">
```

**Nbconvert version: 5.6.1**

**Comment by MSeal** [comment] 2020-05-12 17:22
Thanks for raising, I likely don't have time to dig into the background color issue currently but will review any PRs if someone can determine the cause and make a PR

**Comment by lunluen** [comment] 2020-10-18 04:53
Same here.
In my case, the background stays black, the code syntax highlight is always the same as the default Jupyterlab dark theme, and only the fonts are changed.

CentOS 7, nbconvert 5.6.7

**Comment by benlindsay** [comment] 2020-12-09 23:50
Same problem here, Mac Catalina 10.15.6, looks the same in Chrome and Firefox, nbconvert 6.0.7

**Comment by manmoi01** [comment] 2021-01-05 21:58
Same here, Ubuntu 18.04 nbconvert 5.6.1 and 6.0.7, However it works fine with 5.6.0

**Comment by JanFeld** [comment] 2021-02-20 13:56
Yes it's still here on Arch Linux 5.10.16 with nbconvert 6.0.7.

When defining slide-themes the fonts and colors change except the background colors.

**Comment by piotr-placzek** [comment] 2021-09-07 10:29
Hello after more than year it's still a problem.
Ubuntu 21.04, nbconvert 6.1.0.

**Comment by piotr-placzek** [comment] 2021-09-08 14:18
There is the `.jp-Notebook` class set on the `<body>` attribute. It comes from `JupyterLab` and overrides body background color with white.

For dark theme this combintaion works fine 

`jupyter nbconvert python-introduction.ipynb --to slides --SlidesExporter.reveal_theme=night --SlidesExporter.theme=dark`

Maybe if you will move lines [41](https://github.com/jupyter/nbconvert/blob/main/share/jupyter/nbconvert/templates/reveal/index.html.j2#L41) and [42](https://github.com/jupyter/nbconvert/blob/main/share/jupyter/nbconvert/templates/reveal/index.html.j2#L42) in [this file](https://github.com/jupyter/nbconvert/blob/main/share/jupyter/nbconvert/templates/reveal/index.html.j2) 
under block defined between line [60](https://github.com/jupyter/nbconvert/blob/main/share/jupyter/nbconvert/templates/reveal/index.html.j2#L60) and [66](https://github.com/jupyter/nbconvert/blob/main/share/jupyter/nbconvert/templates/reveal/index.html.j2#L66) of this file or directly above [head closing tag](https://github.com/jupyter/nbconvert/blob/main/share/jupyter/nbconvert/templates/reveal/index.html.j2#L102) into line 101/102,
then this change can fix this issue (?)

**Comment by MSeal** [comment] 2021-09-20 04:25
I believe the 6.2 RC release has this fixed / improved now. Closing

**Closed by MSeal** 2021-09-20 04:25 UTC
Labels: bug, help wanted, format:Slides
