### ISSUE TITLE
Getting output of cells while notebook runs

### ISSUE THREAD

**Issue by mmmaks** [jupyter/nbconvert#848] opened 2018-07-29 07:47 UTC
Hi,
Is there any way to have cells output while the notebook is running with nbconvert??
Currently when I run my .ipynb file through nbconvert, the output file is created when the notebook execution is completed. Is there any way we can see the output of a cell when it completes and not wait for whole notebook to be completed ??

**Comment by t-makaro** [comment] 2019-08-07 00:51
Closing as duplicate of #374.

**Closed by t-makaro** 2019-08-07 00:51 UTC
