### ISSUE TITLE
AttributeError in start_new_kernel using GatewayKernelManager

### ISSUE THREAD

**Issue by golf-player** [jupyter/nbconvert#1195] opened 2020-02-21 17:34 UTC
Here's the full traceback:

    Traceback (most recent call last):
      File "test_nbconvert.py", line 13, in <module>
        ep.preprocess(test_notebook)
      File "/home/plankton/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 403, in preprocess
        with self.setup_preprocessor(nb, resources, km=km):
      File "/home/apkumar/.pyenv/versions/3.6.8/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/home/plankton/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 345, in setup_preprocessor
        self.km, self.kc = self.start_new_kernel(**kwargs)
      File "/home/plankton/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 289, in start_new_kernel
        if km.ipykernel and self.ipython_hist_file:
    AttributeError: 'GatewayKernelManager' object has no attribute 'ipykernel'

I think I can use nbclient instead or something; is it not possible to use a gateway url with nbconvert?

Here's sample code to reproduce:

    from notebook.gateway.managers import GatewayKernelManager, GatewayClient

    from nbconvert.preprocessors import ExecutePreprocessor
    import nbformat

    GatewayClient.url = "http://localhost:8091"
    ExecutePreprocessor.kernel_manager_class = GatewayKernelManager
 
    with open("Untitled.ipynb") as fp:
          test_notebook = nbformat.read(fp, as_version=4)

    ep = ExecutePreprocessor()
    ep.preprocess(test_notebook)

**Nbconvert version:**
5.6.1
**Notebook version:**
6.0.2

**Comment by MSeal** [comment] 2020-02-21 18:52
I don't think there's been testing for the GatewayKernelManager and nbconvert explicitly, or at least not by me (the gateway is relatively new). The error here looks like it's a simple attribute assumption that the GatewayKernelManager isn't adhering to. Should be easy to fix, but the code involved has been moved out to https://github.com/jupyter/nbclient and will be gone from this repo in nbconvert `6.0.0`. Would you mind posting an issue there about supporting / testing GatewayKernelManager?

Something like this is how you can run the same code posted above against the new library (it's almost the same code as nbconvert's 5.6.1 preprocessor still)

```python
from notebook.gateway.managers import GatewayKernelManager, GatewayClient
from nbclient import execute # Or import the NotebookClient here and use the object instead of the function interface

# Seems like this shouldn't be a global constant :/
GatewayClient.url = "http://localhost:8091"

execute_nb("Untitled.ipynb", km=GatewayKernelManager())
```

**Comment by golf-player** [comment] 2020-02-21 19:08
@MSeal I actually just tried the same with nbclient and ran into the same trouble. It seems the kernelmanager nbconvert expects and the GatewayKernelManager are 2 very different things. Just made: https://github.com/jupyter/nbclient/issues/26

**Comment by golf-player** [comment] 2020-02-21 19:35
tbh I'd be happy to try and reconcile GKM with the KernelManagerABC from jupyter_client (I suspect it may not be immediately doable though..)

**Comment by MSeal** [comment] 2020-02-21 22:13
Yeah you've hit on the root cause issue. There was some independent development tracks there that weren't / haven't been full reunified

**Comment by MSeal** [comment] 2020-02-21 22:14
If you do have some time to help fix / improve the situation I'll gladly help get it into the codebase however I can with reviews, merges, and releases.

**Comment by MSeal** [comment] 2020-02-21 22:15
Going to close the issue here in lieu of the nbclient issue as that's where fixes will be applied

**Closed by MSeal** 2020-02-21 22:15 UTC
Labels: upstream
