### ISSUE TITLE
HTML ending tag

### ISSUE THREAD

**Issue by xiyuanbao** [jupyter/nbconvert#942] opened 2019-01-08 18:57 UTC
I am trying to export notebook to html with x3d object generated by mayavi  using nbcovert, but the output cannot display properly.  I compared the source code of notebook page and printed html and realize those ending tags are missing in the latter one, can anyone tell me what to modify and how to modify to get rid of this? Thank you very much!

Here is the segment with all ending tags and it is working:
`<directionallight direction="0 -6.12323e-17 -1" color="1 1 1" intensity="1" on="true" shadowmapsize="1024" znear="-1" zfar="-1" shadowcascades="1" shadowsplitfactor="1" shadowsplitoffset="0.1"></directionallight>`

Here is the segment without ending tags :
`<directionallight direction="0 -6.12323e-17 -1" color="1 1 1" intensity="1" on="true" shadowmapsize="1024" znear="-1" zfar="-1" shadowcascades="1" shadowsplitfactor="1" shadowsplitoffset="0.1">`

The Jinja template I used:
[https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/master/src/jupyter_contrib_nbextensions/templates/nbextensions.tpl](url)

**Comment by xiyuanbao** [comment] 2019-01-08 21:18
I was wrong before, the ending tags are not missing but at wrong position;
Tags can be closed normally until x3d->scene, as is shown below:
![image](https://user-images.githubusercontent.com/32444405/50858596-b01ef200-1345-11e9-83ef-fa3719c09943.png)
But inside scene, when the tags should be parallel:
![screen shot 2019-01-08 at 1 14 02 pm](https://user-images.githubusercontent.com/32444405/50859161-7353fa80-1347-11e9-894f-0c60fc1cd8b8.png)
the output html treats them with different level:
![screen shot 2019-01-08 at 1 16 26 pm](https://user-images.githubusercontent.com/32444405/50859238-abf3d400-1347-11e9-97f8-9c1f635508b9.png)

**Comment by takluyver** [comment] 2019-01-10 13:22
You probably need to ask mayavi or x3d about this; nbconvert is just including HTML generated by one of those tools.

**Comment by MSeal** [comment] 2019-08-09 16:28
Closing as the issue is an upstream problem and hasn't had activity for many months.

**Closed by MSeal** 2019-08-09 16:28 UTC
Labels: upstream
