### ISSUE TITLE
Export notebook to PDF

### ISSUE THREAD

**Issue by josemrzz** [jupyter/nbconvert#1102] opened 2019-09-22 19:31 UTC
The error below appears when trying to print in PDF.

_**nbconvert failed: PDF creating failed, captured latex output:
This is XeTeX, Version 3.14159265-2.6-0.99999 (TeX Live 2018/W32TeX) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
! Undefined control sequence.
<*> .\notebook
              .tex -quiet
? 
! Emergency stop.
<*> .\notebook
              .tex -quiet
No pages of output.
Transcript written on ?.**_

I am sure only this is not helping you much to discover the issue but I don't know what else to post, can you please advice on how I can provide you a proper error log or how to pull the thread a bit more in order to spot the offender?

Thanks,
Jose

**Comment by josemrzz** [comment] 2019-09-22 19:36
When trying directly from anaconda prompt:

**_(base) C:\Users\Chema>jupyter nbconvert --to pdf C:\Users\Chema\Scripts\beta_function.ipynb
[NbConvertApp] Converting notebook C:\Users\Chema\Scripts\beta_function.ipynb to pdf
[NbConvertApp] Support files will be in beta_function_files\
[NbConvertApp] Making directory .\beta_function_files
[NbConvertApp] Making directory .\beta_function_files
[NbConvertApp] Making directory .\beta_function_files
[NbConvertApp] Writing 27814 bytes to .\notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running xelatex 3 times: ['xelatex', '.\\notebook.tex', '-quiet']
[NbConvertApp] CRITICAL | x failed: xelatex .\notebook.tex -quiet
This is XeTeX, Version 3.14159265-2.6-0.99999 (TeX Live 2018/W32TeX) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
! Undefined control sequence.
<*> .\notebook
              .tex -quiet
?
! Emergency stop.
<*> .\notebook
              .tex -quiet
No pages of output.
Transcript written on ?.

Traceback (most recent call last):
  File "C:\Users\Chema\Miniconda3\Scripts\jupyter-nbconvert-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\Chema\Miniconda3\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\Chema\Miniconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\Chema\Miniconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 338, in start
    self.convert_notebooks()
  File "C:\Users\Chema\Miniconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 508, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "C:\Users\Chema\Miniconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 479, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "C:\Users\Chema\Miniconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 408, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "C:\Users\Chema\Miniconda3\lib\site-packages\nbconvert\exporters\exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "C:\Users\Chema\Miniconda3\lib\site-packages\nbconvert\exporters\exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "C:\Users\Chema\Miniconda3\lib\site-packages\nbconvert\exporters\pdf.py", line 187, in from_notebook_node
    raise LatexFailed('\n'.join(self._captured_output))
nbconvert.exporters.pdf.LatexFailed: PDF creating failed, captured latex output:
This is XeTeX, Version 3.14159265-2.6-0.99999 (TeX Live 2018/W32TeX) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
! Undefined control sequence.
<*> .\notebook
              .tex -quiet
?
! Emergency stop.
<*> .\notebook
              .tex -quiet
No pages of output.
Transcript written on ?._**

**Comment by realblack0** [comment] 2019-09-24 04:55
I'm in a same trouble...

**Comment by SBFRF** [comment] 2019-09-28 15:15
having trouble with PDF conversion too

**Comment by josemrzz** [comment] 2019-09-28 20:37
is this thing actually supported?

**Comment by t-makaro** [comment] 2019-09-28 23:05
I believe that the original reported issue is a duplicate of #974. 

@SBFRF I believe you are encountering a different issue, and should open a new issue. It looks like you are not calling the new version of nbconvert, but an old version of nbconvert is finding the new templates. Though I don't know why that would be the case.

**Closed by t-makaro** 2019-09-28 23:05 UTC
Labels: question
