### ISSUE TITLE
Markdown LaTeX conversion issue

### ISSUE THREAD

**Issue by StevenClontz** [jupyter/nbconvert#1519] opened 2021-02-11 20:22 UTC
Dollar signs are converted from Jupyter to LaTeX in an unexpected way.

In a markdown cell:

```
$x^2 + y^2 = z^2$
```

converts to this as intended:

```
\(x^2 + y^2 = z^2\)
```

However:

```
$ x^2 + y^2 = z^2 $
```

converts to this instead:

```
\$ x^2 + y^2 = z^2 \$
```

Note that both original Markdown cells are displayed in math mode as expected in the original notebook.

**Comment by t-makaro** [comment] 2021-02-17 23:51
Duplicate of #749

**Closed by t-makaro** 2021-02-17 23:51 UTC
