### ISSUE TITLE
Cann't download css files

### ISSUE THREAD

**Issue by dongweiming** [jupyter/nbconvert#23] opened 2015-05-17 01:35 UTC
Install notebook but display this error:

```python
    Complete output from command /Users/dongweiming/.virtualenvs/jupyter_notebook/bin/python -c "import setuptools, tokenize; __file__='/Users/dongweiming/.virtualenvs/jupyter_notebook/src/nbconvert/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps:
    running develop
    running css
    Failed to download css from https://cdn.jupyter.org/notebook/4.0.0-dev/style/style.min.css: [Errno socket error] [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
    error: None
    
    ----------------------------------------
    Command "/Users/dongweiming/.virtualenvs/jupyter_notebook/bin/python -c "import setuptools, tokenize; __file__='/Users/dongweiming/.virtualenvs/jupyter_notebook/src/nbconvert/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps" failed with error code 1 in /Users/dongweiming/.virtualenvs/jupyter_notebook/src/nbconvert
```

i have to use `http://` instead of `https://`

**Comment by takluyver** [comment] 2015-05-17 01:45
This looks like a duplicate of #21, though it's interesting that it works with http. Let's continue the discussion on that.

**Closed by takluyver** 2015-05-17 01:45 UTC
