### ISSUE TITLE
hide_input template not working

### ISSUE THREAD

**Issue by paulperry** [jupyter/nbconvert#163] opened 2015-11-27 18:44 UTC
Regular HTML or PDF output works, but adding the --template hide_input or --template hide_input.tpl fails.  The template file is in the path and should be loadable.  

```
>ipython nbconvert test.ipynb --template hide_input.tpl --post serve
[NbConvertApp] WARNING | Collisions detected in jupyter_nbconvert_config.py and jupyter_nbconvert_config.json config files. jupyter_nbconvert_config.json has higher priority: {
  "Exporter": {
    "template_path": "['.', '/Users/paulperry/Library/Jupyter/templates'] ignored, using [u'/Users/paulperry/Library/Jupyter/templates']"
  }
}
[NbConvertApp] Converting notebook test.ipynb to html
[NbConvertApp] WARNING | Unexpected exception loading template: hide_input.tpl
Traceback (most recent call last):
  File "/Users/paulperry/anaconda/lib/python2.7/site-packages/nbconvert/exporters/templateexporter.py", line 177, in _load_template
    template = self.environment.get_template(try_name)
  File "/Users/paulperry/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/paulperry/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 786, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/paulperry/anaconda/lib/python2.7/site-packages/jinja2/loaders.py", line 405, in load
    return loader.load(environment, name, globals)
  File "/Users/paulperry/anaconda/lib/python2.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/paulperry/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 565, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/Users/paulperry/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/paulperry/Library/Jupyter/templates/hide_input.tpl", line 15, in <module>
    {{ super() | strip_output_prompt }}
TemplateAssertionError: no filter named 'strip_output_prompt'
[NbConvertApp] WARNING | Unexpected exception loading template: hide_input.tpl
Traceback (most recent call last):
  File "/Users/paulperry/anaconda/lib/python2.7/site-packages/nbconvert/exporters/templateexporter.py", line 177, in _load_template
    template = self.environment.get_template(try_name)
  File "/Users/paulperry/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/paulperry/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 786, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/paulperry/anaconda/lib/python2.7/site-packages/jinja2/loaders.py", line 405, in load
    return loader.load(environment, name, globals)
  File "/Users/paulperry/anaconda/lib/python2.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/paulperry/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 565, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/Users/paulperry/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/paulperry/Library/Jupyter/templates/hide_input.tpl", line 15, in <module>
    {{ super() | strip_output_prompt }}
TemplateAssertionError: no filter named 'strip_output_prompt'
Traceback (most recent call last):
  File "/Users/paulperry/anaconda/bin/ipython", line 6, in <module>
    sys.exit(start_ipython())
  File "/Users/paulperry/anaconda/lib/python2.7/site-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/paulperry/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 592, in launch_instance
    app.start()
  File "/Users/paulperry/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 349, in start
    return self.subapp.start()
  File "/Users/paulperry/anaconda/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 286, in start
    self.convert_notebooks()
  File "/Users/paulperry/anaconda/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 409, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/Users/paulperry/anaconda/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 380, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources)
  File "/Users/paulperry/anaconda/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 332, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/Users/paulperry/anaconda/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 166, in from_filename
    return self.from_notebook_node(nbformat.read(f, as_version=4), resources=resources, **kw)
  File "/Users/paulperry/anaconda/lib/python2.7/site-packages/nbconvert/exporters/html.py", line 65, in from_notebook_node
    return super(HTMLExporter, self).from_notebook_node(nb, resources, **kw)
  File "/Users/paulperry/anaconda/lib/python2.7/site-packages/nbconvert/exporters/templateexporter.py", line 206, in from_notebook_node
    raise IOError('template file "%s" could not be found' % self.template_file)
IOError: template file "hide_input.tpl" could not be found

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

>
```

I'm on platform : osx-64,  conda version : 3.18.6, conda-build version : 1.13.0, python version : 2.7.10.final.0, Anaconda 2.2.0 (x86_64), IPython 4.0.0 , with nbextensions installed.

**Comment by takluyver** [comment] 2015-12-01 16:52
I think this message might be relevant:

> Collisions detected in jupyter_nbconvert_config.py and jupyter_nbconvert_config.json config files. jupyter_nbconvert_config.json has higher priority

It can read config from both a JSON file and a Python file, but if the same value is set in both, the value in the JSON file takes precedence. And the `template_path` configured by the JSON config file doesn't include the cwd (`.`).

**Comment by paulperry** [comment] 2015-12-01 17:08
hide_input.tpl is a default template and in the template directory, and in the JSON config path.  While it could be an issue, I didn't think it was relevant to this current failure.

**Comment by takluyver** [comment] 2015-12-01 17:33
Sorry, you're right that that's not the failure, I was looking at the wrong error. I'm sure I fixed it before so it doesn't say "can't be found" on an invalid template, but that problem seems to be back.

Your template appears to be looking for a filter that's not there - you can see the list of filters we provide here: https://github.com/jupyter/nbconvert/blob/master/nbconvert/exporters/templateexporter.py#L26

Where did you get the template from? I don't think it's one that comes with nbconvert.

**Comment by paulperry** [comment] 2015-12-01 17:39
I installed the nbextensions, which comes with the following templates: https://github.com/ipython-contrib/IPython-notebook-extensions/tree/master/templates .

**Comment by juhasch** [comment] 2015-12-01 17:48
For the `hide_input.tpl` template you need  to have `strip_output_prompt.py` in your Python path,which can be found in `\nbextensions\usability\hide_input`.

**Comment by takluyver** [comment] 2015-12-01 17:50
Thanks @juhasch .

It sounds like we might need to think a bit more about how extra templates are exposed, so they can be bundled with filters easily. Any thoughts are welcome, but I'll close this issue for now as it doesn't appear to be a bug in nbconvert.

**Closed by takluyver** 2015-12-01 17:50 UTC

**Comment by juhasch** [comment] 2015-12-01 18:02
`strip_output_prompt.py` should probably be in the `IPython-notebook-extensions/extensions` directory, where other Python files like pre- and postprocessors are located. 

We need a better installer for the extensions. Also, something seems to write the template path to the JSON config file sometimes, not sure why. 

@paulperry : If you remove the `template_path` entry in the .py config file the warning message will go away. Also, copy `strip_output_prompt.py` to the `IPython-notebook-extensions/extensions`  directory and it should work.

**Comment by paulperry** [comment] 2015-12-01 22:12
@juhasch I really tried to get this to work, but I couldn't.  
1 - Commenting out the `c.Exporter.template_path` in the `.jupyter/jupyter_nbconvert_config.py` file worked and removed the collision warning.
2 - I copied `strip_output_prompt.py` to about every relevant `extensions` folder I could find (anaconda has many), but could not make it work.

**Comment by diazona** [comment] 2016-03-22 15:45
FWIW I can confirm (some of) this: copying `strip_output_prompt.py` to a directory on `PYTHONPATH` doesn't fix the error. And I checked that the module was actually on the path and importable from within Python. Putting it in the `extensions` directory (in my case, `$HOME/Library/Jupyter/extensions/` since I'm on a Mac) doesn't work either. @juhasch Is there an issue report about this in the IPython-notebook-extensions repository that I could contribute to?

**Comment by juhasch** [comment] 2016-03-22 16:44
I did not create the `hide_input.tpl' template. As far as I understand it, you have to register the `strip_output_prompt` filter with Jinja. I don't know how this is done.

**Comment by diazona** [comment] 2016-03-29 10:22
@juhasch Great, thanks! I'll work with that.
