### ISSUE TITLE
Fatal error occurred: #1->\CYREREV

### ISSUE THREAD

**Issue by Akarazeev** [jupyter/nbconvert#463] opened 2016-11-11 19:11 UTC
[test(ipynb).txt](https://github.com/jupyter/nbconvert/files/586568/test.ipynb.txt)

After the execution of command: `jupyter nbconvert test.ipynb --to latex test.ipynb` I received this file [test(tex).txt](https://github.com/jupyter/nbconvert/files/586512/test.tex.txt).

And only then I use `pdflatex test.tex` to get test.pdf.
But before that I need to replace `\usepackage[T1]{fontenc}` with `\usepackage[T2A]{fontenc}` to avoid problem with cyrillic (russian) characters.

When I tried to execute `jupyter nbconvert test.ipynb --to pdf` I got this:
> ~/Desktop$ jupyter nbconvert test.ipynb --to pdf
[NbConvertApp] Converting notebook test.ipynb to pdf
[NbConvertApp] Writing 14914 bytes to notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running pdflatex 3 times: [u'pdflatex', u'notebook.tex']
[NbConvertApp] CRITICAL | pdflatex failed: [u'pdflatex', u'notebook.tex']
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./notebook.tex
LaTeX2e <2016/03/31>
Babel <3.9r> and hyphenation patterns for 83 language(s) loaded.
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/size11.clo))
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/fontenc.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/t1enc.def))
(/usr/local/texlive/2016/texmf-dist/tex/latex/psnfss/palatino.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(/usr/local/texlive/2016/texmf-dist/tex/latex/pdftex-def/pdftex.def
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/ltxcmds.sty))))
(/usr/local/texlive/2016/texmf-dist/tex/latex/caption/caption.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/caption/caption3.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/adjustbox/adjustbox.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/usr/local/texlive/2016/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(/usr/local/texlive/2016/texmf-dist/tex/generic/xkeyval/xkvutils.tex)))
(/usr/local/texlive/2016/texmf-dist/tex/latex/adjustbox/adjcalc.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/adjustbox/trimclip.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/collectbox/collectbox.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/adjustbox/tc-pdftex.def))
(/usr/local/texlive/2016/texmf-dist/tex/latex/ifoddpage/ifoddpage.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/varwidth/varwidth.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics-cfg/color.cfg))
(/usr/local/texlive/2016/texmf-dist/tex/latex/tools/enumerate.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/usr/local/texlive/2016/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsmath/amstext.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsmath/amsopn.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsfonts/amssymb.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/textcomp.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/ts1enc.def))
(/usr/local/texlive/2016/texmf-dist/tex/latex/upquote/upquote.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/eurosym/eurosym.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/ucs/ucs.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/ucs/data/uni-global.def))
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/inputenc.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/ucs/utf8x.def))
(/usr/local/texlive/2016/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
Style option: 'fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix 
<2008/02/07> (tvz))
(/usr/local/texlive/2016/texmf-dist/tex/latex/oberdiek/grffile.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/oberdiek/kvoptions.sty
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/etexcmds.sty
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/hyperref/hyperref.sty
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/oberdiek/auxhook.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/usr/local/texlive/2016/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
(/usr/local/texlive/2016/texmf-dist/tex/latex/url/url.sty))
Package hyperref Message: Driver (autodetected): hpdftex.
(/usr/local/texlive/2016/texmf-dist/tex/latex/hyperref/hpdftex.def
(/usr/local/texlive/2016/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/tools/longtable.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/booktabs/booktabs.sty)
(/usr/local/texlive/2016/texmf-dist/tex/generic/ulem/ulem.sty)
No file notebook.aux.
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/ts1cmr.fd)
(/usr/local/texlive/2016/texmf-dist/tex/latex/psnfss/t1ppl.fd)
(/usr/local/texlive/2016/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/local/texlive/2016/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/oberdiek/grfext.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
(/usr/local/texlive/2016/texmf-dist/tex/latex/caption/ltcaption.sty)
>*geometry* driver: auto-detecting
*geometry* detected driver: pdftex
*geometry* verbose mode - [ preamble ] result:
* driver: pdftex
* paper: <default>
* layout: <same size as paper>
* layoutoffset:(h,v)=(0.0pt,0.0pt)
* modes: 
* h-part:(L,W,R)=(72.26999pt, 469.75502pt, 72.26999pt)
* v-part:(T,H,B)=(72.26999pt, 650.43001pt, 72.26999pt)
* \paperwidth=614.295pt
* \paperheight=794.96999pt
* \textwidth=469.75502pt
* \textheight=650.43001pt
* \oddsidemargin=0.0pt
* \evensidemargin=0.0pt
* \topmargin=-37.0pt
* \headheight=12.0pt
* \headsep=25.0pt
* \topskip=11.0pt
* \footskip=30.0pt
* \marginparwidth=59.0pt
* \marginparsep=10.0pt
* \columnsep=10.0pt
* \skip\footins=10.0pt plus 4.0pt minus 2.0pt
* \hoffset=0.0pt
* \voffset=0.0pt
* \mag=1000
* \@twocolumnfalse
* \@twosidefalse
* \@mparswitchfalse
* \@reversemarginfalse
* (1in=72.27pt=25.4mm, 1cm=28.453pt)
(/usr/local/texlive/2016/texmf-dist/tex/latex/ucs/ucsencs.def)
(/usr/local/texlive/2016/texmf-dist/tex/latex/hyperref/nameref.sty
(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsfonts/umsa.fd)
(/usr/local/texlive/2016/texmf-dist/tex/latex/amsfonts/umsb.fd)
LaTeX Warning: No \author given.
(/usr/local/texlive/2016/texmf-dist/tex/latex/psnfss/t1pcr.fd)
(/usr/local/texlive/2016/texmf-dist/tex/latex/ucs/data/uni-4.def)
! Undefined control sequence.
\u-default-1069 #1->\CYREREV 
                             
>l.279 ...h{} Это русский коммент}
                                                  
>? 
! Emergency stop.
\u-default-1069 #1->\CYREREV 
                             
>l.279 ...h{} Это русский коммент}
                                                  
>!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on notebook.log.

Also when I tried to save my ipython notebook as PDF: File -> Download as -> PDF via LaTeX (.pdf), I received this Internal Server Error:
<img width="1068" alt="screen shot 2016-11-11 at 22 07 13" src="https://cloud.githubusercontent.com/assets/11920213/20226986/6a04d5ac-a85b-11e6-8c96-00a3154642a4.png">

Today I found out the solution of this issues:
1. replace `\usepackage[T1]{fontenc}` with `\usepackage[T2A]{fontenc}` in the nbconvert/templates/latex/base.tplx
2. small changes in file nbconvert/nbconvert/exporters/pdf.py

**Comment by takluyver** [comment] 2016-11-11 19:24
We've switched to xelatex in master, which I think works better with a range of characters. Can you try with master, and/or do you have a notebook you're willing to share that demonstrates this issue?

**Comment by Akarazeev** [comment] 2016-11-11 19:27
Yes, I have a notebook which demonstrates this issue

**Comment by takluyver** [comment] 2016-11-11 19:41
Thanks! With xelatex on master, it builds OK but the cyrillic characters in the comment don't show up.

@michaelpacer, can you have a look at this? It seems like something you'd be good at. I've put the example notebook above [in a gist](https://gist.github.com/takluyver/57498bc9352c253c668fb589306c8683) to make it easier to download.

**Comment by Akarazeev** [comment] 2016-11-11 20:10
Example of notebook with [russian header](https://gist.github.com/Akarazeev/4ad8ad8223f9376c839f12fd6ceaa384).

Thank you for your attention to this problem!

**Comment by michaelpacer** [comment] 2016-11-11 21:51
This builds without error without any change when you convert to pdf using the current beta release of nbconvert (as well as on master). 

If you want the beta release, and you use pip then you can use

    pip install --pre nbconvert

However, it does not display the characters but that's a more general issue with supporting non-Latin fonts: https://github.com/jupyter/nbconvert/issues/409.

**Comment by michaelpacer** [comment] 2016-11-11 22:04
Since the issue is primarily about the failure, and it doesn't fail on master or the most up to date (beta) release, I'm going to close the issue.

If you would like, you should open a new issue specifically requesting support for cyrillic character sets/fonts (this way it can be looped into the larger conversation and demonstrate the importance of non-Latin character set support in the community). 

Also if you want to write a custom exporter there are instructions here: http://nbconvert.readthedocs.io/en/latest/external_exporters.html

**Closed by michaelpacer** 2016-11-11 22:04 UTC
Labels: Latex, nonlatin_scripts

**Comment by takluyver** [comment] 2016-11-11 22:08
@michaelpacer thanks for that. Can you have a look at the changes in #464 to see if there's anything we should be doing from that? If not, feel free to close it too.
