### ISSUE TITLE
PDF conversion choke on some bytes  (ansi sequences.??)

### ISSUE THREAD

**Issue by Carreau** [jupyter/nbconvert#228] opened 2016-02-04 06:25 UTC
cf [notebook](https://github.com/mjbright/jupyter_notebooks/blob/bc9663c748ae14822c298036798e23c31261a6d9/2016-Feb_Docker_Build_Lab/2016-Feb_Docker_Build_Lab.ipynb) reference in [this comment](https://github.com/jupyter/notebook/issues/840#issuecomment-179646131).

```
 Package inputenc Error: Keyboard character used is undefined
(inputenc)                in inputencoding `utf8x'.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.1444 ^^[[0B

?
! Emergency stop.
 ...

l.1444 ^^[[0B
```

**Comment by takluyver** [comment] 2016-02-04 10:25
The offending bit is the output of a docker command:

```
    \begin{Verbatim}[commandchars=\\\{\}]
{\color{incolor}In [{\color{incolor}35}]:} docker push dockerlabs/toolset:userN
\end{Verbatim}

    \begin{Verbatim}[commandchars=\\\{\}]
The push refers to a repository [docker.io/dockerlabs/toolset]

[0B
[0B
[3BuserN: digest: sha256:8a2e3f3fae154e60e95adbbe95d4e67ada66c64adfbdbde4f5e56e8a56ac8a41 size: 3658
    \end{Verbatim}
```

It's not rendered correctly in [the notebook on Github](https://github.com/mjbright/jupyter_notebooks/blob/bc9663c748ae14822c298036798e23c31261a6d9/2016-Feb_Docker_Build_Lab/2016-Feb_Docker_Build_Lab.ipynb), either, but it doesn't break the whole document.

**Comment by minrk** [comment] 2016-02-04 21:21
Would #225 fix this?

**Comment by mgeier** [comment] 2016-02-05 09:03
I believe it would, since it removes all sequences starting with `'\x1b['` and ending with an ASCII letter in the range `[@-~]`.

According to [Wikipedia](https://en.wikipedia.org/wiki/ANSI_escape_code#Sequence_elements), there are also two-character sequences consisting of `'\x1b'` followed by one character in the range `[@-_]`. Those are still not handled.

And there seems to be an alternative starting character `'\x9b'` (used instead of `'\x1b['`), which isn't handled either.

I don't understand the details and I don't know if any of this is used in practice, but if needed, I can add support for those cases, too.

**Comment by mgeier** [comment] 2016-02-05 10:18
I still don't completely understand this: the notebook linked above contains several occurrences of `'\x1b[2K'`, which are meant to clear the current line (e.g. for the display of download progress).

Strangely, this actually works!

At which point in the conversion process is this done?
Is this part of `nbformat` or `nbconvert` or something entirely different?

Probably the problem discussed here should be fixed wherever that happens.

The fragments which appear here seem to be from `\x1b[0B`, which is supposed to mean "move the cursor down zero cells", which I guess should be handled wherever clearing lines happens.

Either way, if some ANSI-sequences are not properly handled, they will be filtered out by #225, which is probably not even the desired behavior, since those cases should have been handled earlier?

**Comment by mgeier** [comment] 2016-02-14 19:55
I had another look and I found out that things like `'\x1b[2K'` are not actually properly handled, but in the example notebook mentioned above there are many `'\r'` characters (without `'\n'`), which seem to erase many lines.
I still don't know where exactly those `'\r'` are deleting stuff ... `nbformat.read()` still shows all the lines, in the resulting HTML file they are gone ... somewhere in-between they must be "swallowed" ... can anybody tell me where/how this is happening?

In any case, #225 will remove all those ANSI escape sequences.

**Comment by takluyver** [comment] 2016-02-14 21:07
I think it's `nbconvert.preprocessors.coalescestreams` that handles carriage returns. And I guess it's just a historical artifact that that's done in a completely separate place to ansi handling.

**Comment by mgeier** [comment] 2016-02-21 09:58
Thanks @takluyver, I wasn't aware of that preprocessor. It seems a bit obscure to me why this is done ... the [docstring](https://github.com/jupyter/nbconvert/blob/2279503d641f0c8321ac29bd82ff0b36d1cdacf2/nbconvert/preprocessors/coalescestreams.py#L39) says:

    Merge consecutive sequences of stream output into single stream
    to prevent extra newlines inserted at flush calls

What are those "flush calls"?
If I use `print('...', flush=True)`, no separate streams are created in the notebook file.

Is this preprocessor really necessary?

I saw that the live notebook also combines neighboring streams when loading a notebook, but I'm not sure if that's the expected behavior.
If a notebook has separate streams, why shouldn't they be displayed as such?

Do multiple consecutive streams even happen in practice?

**Comment by takluyver** [comment] 2016-02-21 10:53
I think the main reason for it is to deal with things that do line-rewriting using carriage return, like progress bars. If we just passed the raw data through to output formats, they would mostly display every stage of the progress bar line by line. So coalescestreams turns `1\r2\r3` into `3`.

Where there are consecutive stream outputs from the same stream, it also joins them into one output, making the notebook structure smaller. That's necessary for the carriage return handling to work properly.

**Comment by mgeier** [comment] 2016-02-21 11:59
OK, I understand removing `'\r'`, we could easily move that to the ANSI filters.

I still don't understand why consecutive streams should be combined.
Conceptually, if there are separate streams in the notebook file, I'd also expect separate streams in the `nbconvert` output ...

And if those consecutive streams are actually meant to be combined, shouldn't that happen at a completely different place, namely when creating the notebook representation?

And how can it happen in the first place that separate streams come into being if they are intended as a single stream?

Does this ever happen?

**Comment by takluyver** [comment] 2016-02-21 13:17
It's not separate streams, it's separate *stream outputs* on one stream. By the nature of a stream, joining the chunks within the stream should not make a semantic difference - streams do not have any inherent chunks, that's just a detail of how we deal with the data. However, to deal with carriage returns correctly, we have to combine them, so that a carriage return in one message can erase the line from a previous message.

When running a notebook interactively, I think some of the server or JS machinery does something equivalent to concatenate consecutive stream outputs (though I don't think it processes carriage returns, though). But when you run a notebook with `nbconvert --execute`, the coalesceoutput preprocessor is what does it. Maybe it could be combined into the execute preprocessor, but I don't see any particular advantage to doing so.

**Comment by mgeier** [comment] 2016-02-21 17:16
> joining the chunks within the stream should not make a semantic difference

OK, now I get the relation between `coalesce_streams` and removing `'\r'`.
But I still don't know if this will ever be actually needed in the real world.

My suggestion would be to move the `'\r'`-processing to the ANSI filters and to remove the rest of `coalesce_streams` completely.

Is there any real use of a stream that's separated into multiple chunks?

Even if there is, is there ever a stream chunk that doesn't end with `'\n'`?

And even if there is a chunk not ending in `'\n'` followed by a chunk containing `'\r'` in the first line, isn't it the fault of who-/whatever created the file that the stream is split into chunks instead of keeping it whole?

To me this seems like a much too exotic edge case to warrant its own preprocessor.

> Maybe it could be combined into the execute preprocessor ...

AFAIK, `coalesce_streams` is not only executed with `nbconvert --execute`, but in all conversions. Therefore, it will not be possible to move the code to the "execute" preprocessor anyway.

**Comment by takluyver** [comment] 2016-02-21 18:27
> Is there any real use of a stream that's separated into multiple chunks?
> Even if there is, is there ever a stream chunk that doesn't end with '\n'?

Progress bars, for instance. In order for the user to see it as intended, the output that produces each step has to go over as an independent chunk, and then the next chunk overwrites it.

And more generally, while stream messages will often be line-by-line, there's no particular reason why that needs to be so, and I don't consider it an edge case if they're not.

I'm not sure why this is a problem, though. Again, the semantics of streams shouldn't be affected on chunking or concatenating them.

**Comment by mgeier** [comment] 2016-02-22 15:04
I created a PR to move carriage-return processing to the ANSI filters: #252

Regarding stream chunking, it seems to me that you're talking about the communication between kernel and notebook. There may be several chunks which are sent and displayed at different time instances.

What I'm talking about, is how those streams are stored in notebook files.

I tried different ways of creating progress bars, and none of them resulted in more than one stream chunk stored in the notebook file.

I'm not saying that it's a bad idea to concatenate the stream chunks, I'm just asking if there is at least one real-world situation where multiple stream chunks are generated. Is there?

Incidentally, the different ways of creating progress bars resulted in quite different data stored in the notebook file (and different behavior observable in the browser):

* When using a `%%bash` cell with `echo` and `sleep`, all partial lines (including the `\r` characters) are stored in the notebook file. In the browser, the "animation" is *not* visible, only the last line shows up in the end.
* The same happens when using the same bash code in a file called by `bash myfile.sh` within a `%%bash` cell. The "animation" is *not* visible in the browser.
* When calling `!bash myfile.sh` in a normal Python3 cell, only the final line is stored in the notebook file (without any `\r` characters). The "animation" is *not* visible in the browser.
* When `print()`ing the progress lines directly with Python3, again, only the final line is stored (without any `\r` characters). This is the only case where the "animation" is actually visible in the browser.
* If I print the progress lines with `!echo ...` from within a Python3 cell, again, only the final line is stored (without any `\r` characters). The "animation" is *not* visible in the browser.

Because of the different behaviors, I assume that different code paths are taken, although everything should be the same old kernel-agnostic `stdout` stream.
IMHO the desired behavior is that the `\r` characters are stripped beforehand and only the lines shown in the end are actually stored in the notebook file.

Also, it would be nice to see the "animation" in all the cases described above, but I guess this is a different issue (to be discussed later).

I had a look how streams are handled in the Jupyter Notebook:
I found the JavaScript function `append_stream()`: https://github.com/jupyter/notebook/blob/46d8784afbfd75b76440875a468291060c38c911/notebook/static/notebook/js/outputarea.js#L469
This combines stream chunks and takes care of carriage-returns and ANSI escape sequences.
I didn't find anything else. I'm not very good at JavaScript, so I don't know where and when exactly this is called.
Does this have an influence on how streams are stored in the notebook file or is this handled somewhere else?

Is it possible that the IPython kernel does some additional stream processing?

If yes, shouldn't this be moved to the `notebook` itself in order for all kernels to benefit from it?

> I'm not sure why this is a problem ...

It's not really a problem, I just want to understand how this works (and more importantly, how it is *supposed* to work), because probably at some point I'll try to implement the handling of ANSI movement commands in the Notebook. But I'd only want to do that if it is possible to implement it in a kernel-agnostic way.

**Comment by takluyver** [comment] 2016-02-22 15:34
Output messages sent from the kernel correspond to outputs stored in the notebook file format. So separate stream messages may result in separate stream outputs stored in the notebook file (though they don't necessarily).

The function you found does the equivalent of coalescestreams in JS. It does affect what gets stored in the notebook file, but only if the notebook was executed interactively and then saved. If you execute it using the execute preprocessor in nbconvert, that function is not being run (no JS is, unless it happens to use a JS kernel). So coalescestreams is the equivalent for that case - and for any other case where an input notebook may have separate stream chunks.

**Comment by mgeier** [comment] 2016-02-24 11:45
Sorry that it took me so long, but I think now I finally understand!
Thanks for your patience!

I was trying to find stream chunks in `.ipynb` files, but there they hardly ever (or never?) appear.
They regularly appear, however, in the in-memory representation after the `ExecutePreprocessor` is used.

Each Jupyter client is supposed to take care of concatenating the stream chunks on its own, right?

I thought there was some shared code between the live notebook and the `ExecutePreprocessor` (and any other client) to do that, but apparently there's not.

This also means that any additional ANSI handling that I'd like to implement, would have to be implemented (at least) twice, once in JavaScript and once in Python, right?

**Comment by takluyver** [comment] 2016-02-24 11:57
> I thought there was some shared code between the live notebook and the ExecutePreprocessor (and any other client) to do that, but apparently there's not.

They share the `jupyter_client` module which knows about the messaging protocol, and the `nbformat` module which knows about the notebook JSON file format. Adding outputs to the notebook is *mostly* just adding the JSON content of output messages into an array of outputs. They do independently do output coalescing (which is optional in terms of the notebook format) and ANSI escape processing.

> This also means that any additional ANSI handling that I'd like to implement, would have to be implemented (at least) twice, once in JavaScript and once in Python, right?

Yes. And the Qt console has separate ANSI handling as well, last time I checked.

What are you thinking of implementing? I think you mentioned cursor movement before, but I don't really see how that makes sense without a terminal.

**Comment by mgeier** [comment] 2016-02-24 12:19
OK, thanks for confirming my speculations.

I don't have an actual use case, but in the course of the discussion above, I tried the ANSI escape codes for cursor movement and saw that they are not implemented (except, obviously, in the actual terminal client). This was not surprising, because the use case would be quite exotic.
I was just thinking about implementing this for completeness' sake.
But since this apparently would have to be implemented several times in different languages, I lost the motivation to do that.

Apart from not implementing movement, the current solution also "swallows" ANSI color commands that happen before a `\r`, but I guess this is a minor bug with no practical relevance.

I guess I'll just leave it at that ... but I'll try to improve the ANSI code in the live notebook (more appropriate than https://github.com/jupyter/notebook/pull/988), and I'll probably also try the "upgrade" to 16 colors: #245.

Anyway, I think this issue can be closed since #225 already took care of the original problem.

**Comment by takluyver** [comment] 2016-02-24 13:03
I think the cursor movement commands - and various other ANSI escapes like scrolling - can't really work unless you've got something like a terminal at the other end to handle them. The SGR commands (like colours and underlining) are the only ones that really apply to an arbitrary stream of text. And we handle carriage return as a special case, since you can do that by processing lines rather than full terminal emulation.

**Comment by mgeier** [comment] 2016-02-24 17:27
Well it would be definitely doable to implement "up", "down", "left" and "right" movements and the proper "delete line" command. Also the "carriage return" could be implemented correctly, i.e. not actually deleting the line but just positioning the cursor.

But all this isn't worth the effort if it has to be done in each client separately.

The main reason why I started thinking about that is that the notebook linked in the original issue description actually uses the commands for "up", "down" and "delete line".
However, by ignoring them and just implementing "carriage return" we get a very similar result.
I guess the current carriage return handling is sufficient in most (if not all) cases.

**Comment by takluyver** [comment] 2016-02-24 17:36
I've never come across a case where the current handling wasn't good enough.

What do you do with cursor movement if it tries to move beyond the current output? That could get confusing in a hurry.

**Comment by mgeier** [comment] 2016-02-25 15:09
> I've never come across a case where the current handling wasn't good enough.

Just for future reference, the outputs of the notebook that's linked in the original issue description is slightly different in the live notebook, in a HTML page generated with `nbconvert` and in an actual terminal.

e.g. cell no. 35 with the command `docker push dockerlabs/toolset:userN`:

**live notebook:**

```
The push refers to a repository [docker.io/dockerlabs/toolset]

72482fe59c12: Preparing 
5f70bf18a086: Preparing 
userN: digest: sha256:8a2e3f3fae154e60e95adbbe95d4e67ada66c64adfbdbde4f5e56e8a56ac8a41 size: 3658
```

**nbconvert:**

```
The push refers to a repository [docker.io/dockerlabs/toolset]



userN: digest: sha256:8a2e3f3fae154e60e95adbbe95d4e67ada66c64adfbdbde4f5e56e8a56ac8a41 size: 3658
```

**terminal:**

```
The push refers to a repository [docker.io/dockerlabs/toolset]
72482fe59c12: Pushed 
5f70bf18a086: Layer already exists 
b652ec3a27e7: Layer already exists 
userN: digest: sha256:8a2e3f3fae154e60e95adbbe95d4e67ada66c64adfbdbde4f5e56e8a56ac8a41 size: 3658
```

... or another, longer example from cell no. 134 with the command `docker build -t lab/python_flask .`:

**live notebook:**

```
Sending build context to Docker daemon 4.096 kB
Step 1 : FROM python:2.7
2.7: Pulling from library/python

03e1855d4f31: Already exists 
a3ed95caeb02: Already exists 
9269ba3950bb: Already exists 
6ecee6444751: Already exists 
7a0c192d4d25: Already exists 
a3ed95caeb02: Already exists 
7d4cc27b64c3: Pulling fs layer 
Digest: sha256:84d75f33b4ae12997a0a2d51481ed18525ee7b49a5660c3301a00dfb2db19a14
Status: Downloaded newer image for python:2.7
 ---> 31093b2dabe2
Step 2 : MAINTAINER "Docker Build Lab" <dockerlab@mjbright.net>
 ---> Running in fa6f37644a0d
 ---> baf5e793c7e5
Removing intermediate container fa6f37644a0d
Step 3 : WORKDIR /src
 ---> Running in b958687fa4dd
 ---> 27c199001060
Removing intermediate container b958687fa4dd
Step 4 : ADD requirements.txt /src/
 ---> 7ea28cc9002d
Removing intermediate container 14db71be2517
Step 5 : RUN pip install -r requirements.txt
 ---> Running in 85f835fbc058
Collecting flask (from -r requirements.txt (line 1))
  Downloading Flask-0.10.1.tar.gz (544kB)
Collecting redis (from -r requirements.txt (line 2))
  Downloading redis-2.10.5-py2.py3-none-any.whl (60kB)
Collecting Werkzeug>=0.7 (from flask->-r requirements.txt (line 1))
  Downloading Werkzeug-0.11.3-py2.py3-none-any.whl (305kB)
Collecting Jinja2>=2.4 (from flask->-r requirements.txt (line 1))
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
Collecting itsdangerous>=0.21 (from flask->-r requirements.txt (line 1))
  Downloading itsdangerous-0.24.tar.gz (46kB)
Collecting MarkupSafe (from Jinja2>=2.4->flask->-r requirements.txt (line 1))
  Downloading MarkupSafe-0.23.tar.gz
Building wheels for collected packages: flask, itsdangerous, MarkupSafe
  Running setup.py bdist_wheel for flask
  Stored in directory: /root/.cache/pip/wheels/d2/db/61/cb9b80526b8f3ba89248ec0a29d6da1bb6013681c930fca987
  Running setup.py bdist_wheel for itsdangerous
  Stored in directory: /root/.cache/pip/wheels/97/c0/b8/b37c320ff57e15f993ba0ac98013eee778920b4a7b3ebae3cf
  Running setup.py bdist_wheel for MarkupSafe
  Stored in directory: /root/.cache/pip/wheels/94/a7/79/f79a998b64c1281cb99fa9bbd33cfc9b8b5775f438218d17a7
Successfully built flask itsdangerous MarkupSafe
Installing collected packages: Werkzeug, MarkupSafe, Jinja2, itsdangerous, flask, redis
Successfully installed Jinja2-2.8 MarkupSafe-0.23 Werkzeug-0.11.3 flask-0.10.1 itsdangerous-0.24 redis-2.10.5
You are using pip version 7.1.2, however version 8.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
 ---> bb2f3c93b63a
Removing intermediate container 85f835fbc058
Step 6 : ADD . /src
 ---> 498444d5c1f9
Removing intermediate container 9575ea2f7694
Step 7 : CMD python flask_redis_app.py
 ---> Running in 4e4d093beef8
 ---> c261953c57b7
Removing intermediate container 4e4d093beef8
Successfully built c261953c57b7
```

**nbconvert:**

```
Step 1 : FROM python:2.7
2.7: Pulling from library/python








Digest: sha256:84d75f33b4ae12997a0a2d51481ed18525ee7b49a5660c3301a00dfb2db19a14
Status: Downloaded newer image for python:2.7
 ---> 31093b2dabe2
Step 2 : MAINTAINER "Docker Build Lab" <dockerlab@mjbright.net>
 ---> Running in fa6f37644a0d
 ---> baf5e793c7e5
Removing intermediate container fa6f37644a0d
Step 3 : WORKDIR /src
 ---> Running in b958687fa4dd
 ---> 27c199001060
Removing intermediate container b958687fa4dd
Step 4 : ADD requirements.txt /src/
 ---> 7ea28cc9002d
Removing intermediate container 14db71be2517
Step 5 : RUN pip install -r requirements.txt
 ---> Running in 85f835fbc058
Collecting flask (from -r requirements.txt (line 1))
  Downloading Flask-0.10.1.tar.gz (544kB)
Collecting redis (from -r requirements.txt (line 2))
  Downloading redis-2.10.5-py2.py3-none-any.whl (60kB)
Collecting Werkzeug>=0.7 (from flask->-r requirements.txt (line 1))
  Downloading Werkzeug-0.11.3-py2.py3-none-any.whl (305kB)
Collecting Jinja2>=2.4 (from flask->-r requirements.txt (line 1))
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
Collecting itsdangerous>=0.21 (from flask->-r requirements.txt (line 1))
  Downloading itsdangerous-0.24.tar.gz (46kB)
Collecting MarkupSafe (from Jinja2>=2.4->flask->-r requirements.txt (line 1))
  Downloading MarkupSafe-0.23.tar.gz
Building wheels for collected packages: flask, itsdangerous, MarkupSafe
  Running setup.py bdist_wheel for flask
  Stored in directory: /root/.cache/pip/wheels/d2/db/61/cb9b80526b8f3ba89248ec0a29d6da1bb6013681c930fca987
  Running setup.py bdist_wheel for itsdangerous
  Stored in directory: /root/.cache/pip/wheels/97/c0/b8/b37c320ff57e15f993ba0ac98013eee778920b4a7b3ebae3cf
  Running setup.py bdist_wheel for MarkupSafe
  Stored in directory: /root/.cache/pip/wheels/94/a7/79/f79a998b64c1281cb99fa9bbd33cfc9b8b5775f438218d17a7
Successfully built flask itsdangerous MarkupSafe
Installing collected packages: Werkzeug, MarkupSafe, Jinja2, itsdangerous, flask, redis
Successfully installed Jinja2-2.8 MarkupSafe-0.23 Werkzeug-0.11.3 flask-0.10.1 itsdangerous-0.24 redis-2.10.5
You are using pip version 7.1.2, however version 8.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
 ---> bb2f3c93b63a
Removing intermediate container 85f835fbc058
Step 6 : ADD . /src
 ---> 498444d5c1f9
Removing intermediate container 9575ea2f7694
Step 7 : CMD python flask_redis_app.py
 ---> Running in 4e4d093beef8
 ---> c261953c57b7
Removing intermediate container 4e4d093beef8
Successfully built c261953c57b7
```

**terminal:**

```
Sending build context to Docker daemon 4.096 kB
Step 1 : FROM python:2.7
2.7: Pulling from library/python
03e1855d4f31: Already exists 
a3ed95caeb02: Pull complete 
9269ba3950bb: Already exists 
6ecee6444751: Already exists 
7a0c192d4d25: Already exists 
5d45fb7887b4: Already exists 
7d4cc27b64c3: Pull complete 
5345aa49ef1b: Pull complete 
Digest: sha256:84d75f33b4ae12997a0a2d51481ed18525ee7b49a5660c3301a00dfb2db19a14
Status: Downloaded newer image for python:2.7
 ---> 31093b2dabe2
Step 2 : MAINTAINER "Docker Build Lab" <dockerlab@mjbright.net>
 ---> Running in fa6f37644a0d
 ---> baf5e793c7e5
Removing intermediate container fa6f37644a0d
Step 3 : WORKDIR /src
 ---> Running in b958687fa4dd
 ---> 27c199001060
Removing intermediate container b958687fa4dd
Step 4 : ADD requirements.txt /src/
 ---> 7ea28cc9002d
Removing intermediate container 14db71be2517
Step 5 : RUN pip install -r requirements.txt
 ---> Running in 85f835fbc058
Collecting flask (from -r requirements.txt (line 1))
  Downloading Flask-0.10.1.tar.gz (544kB)
Collecting redis (from -r requirements.txt (line 2))
  Downloading redis-2.10.5-py2.py3-none-any.whl (60kB)
Collecting Werkzeug>=0.7 (from flask->-r requirements.txt (line 1))
  Downloading Werkzeug-0.11.3-py2.py3-none-any.whl (305kB)
Collecting Jinja2>=2.4 (from flask->-r requirements.txt (line 1))
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
Collecting itsdangerous>=0.21 (from flask->-r requirements.txt (line 1))
  Downloading itsdangerous-0.24.tar.gz (46kB)
Collecting MarkupSafe (from Jinja2>=2.4->flask->-r requirements.txt (line 1))
  Downloading MarkupSafe-0.23.tar.gz
Building wheels for collected packages: flask, itsdangerous, MarkupSafe
  Running setup.py bdist_wheel for flask
  Stored in directory: /root/.cache/pip/wheels/d2/db/61/cb9b80526b8f3ba89248ec0a29d6da1bb6013681c930fca987
  Running setup.py bdist_wheel for itsdangerous
  Stored in directory: /root/.cache/pip/wheels/97/c0/b8/b37c320ff57e15f993ba0ac98013eee778920b4a7b3ebae3cf
  Running setup.py bdist_wheel for MarkupSafe
  Stored in directory: /root/.cache/pip/wheels/94/a7/79/f79a998b64c1281cb99fa9bbd33cfc9b8b5775f438218d17a7
Successfully built flask itsdangerous MarkupSafe
Installing collected packages: Werkzeug, MarkupSafe, Jinja2, itsdangerous, flask, redis
Successfully installed Jinja2-2.8 MarkupSafe-0.23 Werkzeug-0.11.3 flask-0.10.1 itsdangerous-0.24 redis-2.10.5
You are using pip version 7.1.2, however version 8.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
 ---> bb2f3c93b63a
Removing intermediate container 85f835fbc058
Step 6 : ADD . /src
 ---> 498444d5c1f9
Removing intermediate container 9575ea2f7694
Step 7 : CMD python flask_redis_app.py
 ---> Running in 4e4d093beef8
 ---> c261953c57b7
Removing intermediate container 4e4d093beef8
Successfully built c261953c57b7
```

It seems that the live notebook does a slightly better job than `nbconvert`. And the terminal output is still slightly different.

It also turns out that the ANSI color codes 90–97 and 100–107 are not implemented, which are used in the example notebook.
I'll add support for them in a separate PR, this is probably related to #245.

> What do you do with cursor movement if it tries to move beyond the current output?

If it goes down too far, I'd add new lines, if it goes right too far, I'd add spaces.
If it goes up/left too far, I'd clip it at the first row/column.

> That could get confusing in a hurry.

Well it would sure get more complicated.
There would have to be some custom data structure that stores the formatting for each letter, because the colors might be changed while jumping back and forth.

**Comment by mgeier** [comment] 2016-03-18 09:26
I found a related and very interesting comment/discussion there: https://github.com/jupyter/notebook/pull/506#issuecomment-144996447

I think it would make sense to move the not-color-related ANSI processing to the server, but I don't know if it's technically possible/feasible ...

**Comment by t-makaro** [comment] 2019-06-12 15:56
The notebook mentioned in the first comment appears to convert fine with nbconvert 5.5.0 (except for a list in one of the markdown cells, but that's another issue). I'm closing this issue. Comment to re-open if needed.

**Closed by t-makaro** 2019-06-12 15:56 UTC
Labels: LaTeX
