### ISSUE TITLE
Feature request: output print commands

### ISSUE THREAD

**Issue by eseiver** [jupyter/nbconvert#543] opened 2017-03-06 23:10 UTC
When executing a notebook from the command line, it would be great if it could also output the results of print commands, so that I didn't have to convert the notebook to a .py file to see them.

**Comment by godber** [comment] 2018-06-30 12:35
I am surprised there isn't a lot more enthusiasm for this request. Is there some other way of getting information out of this process at runtime that I am not thinking of?  I guess I could write output to a file.  Maybe there's an `nbconvert.print` that others are using?

**Comment by t-makaro** [comment] 2019-08-07 05:55
Closing as a duplicate of #374. I suppose that this only specifies output of print statements to stdout, and so may not necessarily be considered a duplicate. I believe the conversation may be better suited for there.

**Closed by t-makaro** 2019-08-07 05:55 UTC
