### ISSUE TITLE
Breaking lines in verbatim output in latex export

### ISSUE THREAD

**Issue by amueller** [jupyter/nbconvert#323] opened 2016-06-09 20:53 UTC
For Latex, the output is formatted using the `Verbatim` environment, which doesn't insert line breaks.
If you printed a very long line, or a long text, this is somewhat annoying.
I didn't see a way to make `Verbatim` insert line-breaks. There is the `spverbatim` package that does it though. Would it be possible to change the verbatim package? Or would there be another way to solve this issue?
I think inserting line breaks in output is reasonable - after all, they are broken in the notebook.

Or do you think it would be better to use a filter to enter newlines before passing the text to latex? The filter doesn't know how wide the area will be, though.

**Comment by michaelpacer** [comment] 2016-08-18 02:20
Sounds like this needs a good deal of discussion to figure out how to handle it best. 

I'm guessing you were suggesting changing which verbatim package we use rather than trying to get a change in the upstream verbatim package, which I'm pretty sure would go no where given the tenure of the environment and the tendencies of LATeX2ε.

**Comment by amueller** [comment] 2016-08-18 14:21
Yeah I meant moving from ``Verbatim`` to ``spverbatim``.
Or alternatively use a filter for formatting. Actually, this is an issue in multiple exports, not only latex, I think.

**Comment by michaelpacer** [comment] 2016-09-14 01:16
Is there a Verbatim environment in non-LaTeX output formats? Or just something analogous?

I'm not sure we want to switch verbatim packages for only this reason.

Is the reason why this isn't a problem in the live notebook that the output box becomes an inset area with its own scrollable controls? If so, I'm not sure we want to provide line breaks. I fear that there may be no way to solve this problem in a non-interactive static document since line breaks can be meaningful in output (say, if the output actually is supposed to be interpreted as python code) so we can't just break lines throughout without changing the meaning.

If we wanted to template it it would require not only thinking about the width of the final box (in LaTeX) but also about the size of the font that we choose… in some ways it might be easier (since everything in the Verbatim environment will be printed as monospace anyway) to count the number of characters that we can expect to fill at most in a line and work with that.

**Comment by amueller** [comment] 2016-09-14 16:24
Well, there is ``preformatted`` environments in other exports, and they have the same issues (in markdown and asciidoc at least. I think html is not using ``<pre>`` so it's not a problem there)

I think in the live notebook the html just wraps lines.

I'm not sure about the meaningful line breaks. you can't ensure line breaks in the live notebook.... so if I print a really long line of python code, it will be wrapped. What does it mean though to have a line of python code? What's the mime type of that? I was talking about plain text.

**Comment by carlthome** [comment] 2016-10-24 17:31
I'm also interested in something like this. It would be nice if the LaTeX output didn't have so many overfull boxes caused by code cells.

**Comment by amueller** [comment] 2016-10-24 17:49
@carlthome code cells or output cells? I didn't have issues with codecells because I broke them manually in accordance with pep8 ;)

**Comment by carlthome** [comment] 2016-10-24 20:32
Jupyter is not only for Python and some languages have longer line lengths. Also, even 80 is too much for IEEETran.

**Comment by amueller** [comment] 2016-10-24 20:35
Yeah it's actually also too long for my book. I guess "nicely" breaking code is harder though, in particular in python land where whitespace is significant.
What were you thinking of? Using a language specific tool?

**Comment by carlthome** [comment] 2016-10-24 20:38
Honestly wouldn't mind if the LaTeX is readable at the cost of language legal formatting, but that's because I'm mostly intending to use nbconvert for pseudo-code like examples that are almost language agnostic.

**Comment by cknoll** [comment] 2017-01-20 18:50
I was just affected by this issue. Is there any known workarround?

**Comment by amueller** [comment] 2017-01-20 18:52
@cknoll write a post-processor for your template

**Comment by cknoll** [comment] 2017-01-20 18:58
Sounds reasonable. Do you have a link to the docs at hand?
BTW: I solved my current issue by using html as output format, which is OK in this special case.

**Comment by amueller** [comment] 2017-01-20 18:58
I edited my comment above to include what I did

**Comment by cknoll** [comment] 2017-01-20 18:59
Wow. Thanks!

**Comment by amueller** [comment] 2017-01-20 19:01
Uh this also includes stuff for the "hide_input" plugin which I ended up not using. So yeah most of the template is kinda useless. but I think you get the places where I added the ``break_lines``.

**Comment by hoangvanthien** [comment] 2017-07-02 13:57
@amueller It looks cool. Can you tell me how to get this postprocessor working? When I run the nbconvert command I can choose template but how can I choose postprocessor? :/

**Comment by amueller** [comment] 2017-07-05 14:44
@hoangvanthien not sure I understand your question. My method doesn't use a post-processor, it uses a custom exporter.

**Comment by hoangvanthien** [comment] 2017-07-06 17:28
@amueller Danke! I used your files modified a bit. You said in your comment that "write a post-processor", made me thought that the code is the post-processor. But anyway while you were away, I found out that I should use it as an exporter and I successfully handled the error.

I think this change should be made directly in latex exporter as well as the default template. If you don't mind, let me try to play around with this and make a pull request soon, how's that?

**Comment by mpacer** [comment] 2017-07-07 01:10
I've been working on trying to get at this another way. Specifically since
in python white space is meaningful we can't just break lines in the
traditional sense.

Better is using autopep8 or yapf on the code directly. This allows directly
manipulating the code itself to ensure that it is valid for the number of
characters expected, rather than just wrapping the lines. If you want I can
keep you aprised.

But, you should take a stab at implementing it as a PR even if we go in
this other direction.

**Comment by amueller** [comment] 2017-07-07 15:07
@mpacer this is not about code, it's about raw text iirc.
If you print a really long string, it will be wrapped in the cell in the notebook and html conversion, but just run over in the latex.

**Comment by mpacer** [comment] 2017-07-07 20:17
@amueller Sorry my memory of this issue is clouded by having people running into the same overflow issue with the source in code cell inputs (particularly in educational contexts where students aren't necessarily being graded on adherance to pep8 style).

I wonder if it might make sense to make a `display` or `DisplayObject` subclass that would allow you to correctly bypass the resulting <pre> tag…

I'm actually coming around to the idea of text/plain-text output not needing to be treated as "code" in the traditional sense (i.e., in a different way from cell inputs).

**Comment by t-makaro** [comment] 2018-03-04 18:33
Sphinx found a solution by [modifying fancyvrb's verbatim](https://github.com/sphinx-doc/sphinx/pull/2343/files) environment. I've been exploring my own solutions [here](https://github.com/t-makaro/nb_pdf_template/issues/3). I solution for code cells is difficult, but should be much easier for output cells.

**Comment by t-makaro** [comment] 2018-09-01 02:52
Word wrapping output is easy (I found a simple solution of using a wordwrap filter works nicely). I have recently found a way to word wrap the highlighted code. 

The only reasonable solution that I have found it to use latex's minted package to control highlighting. This would involve a fairly large rewrite to the codebase (mostly removing code since we won't need to control the highlighting ourselves), and it is not compatible with the current method of inserting spaces to make room for the prompt, but here is a taste of the resulting pdf:

![image](https://user-images.githubusercontent.com/18018386/44941614-59c9f300-ad56-11e8-8a10-8ea79db05b93.png)

Notice that a line continuation character is drawn where the line breaks giving a clear indication that the newline should not be treated as syntax.

**Comment by mgeier** [comment] 2018-10-03 18:20
For the record, I just created a PR for `nbsphinx` (https://github.com/spatialaudio/nbsphinx/pull/218) that uses the line-breaking feature @t-makaro mentioned above (https://github.com/jupyter/nbconvert/issues/323#issuecomment-370251911).

I personally try to break my input code manually to a reasonable length, but I guess it's nice to have the wrapping just in case. And of course for cell output this is good to have.

What's IMHO even greater about the Sphinx solution is the page breaking. But this issue isn't about that ...

**Comment by t-makaro** [comment] 2018-10-03 19:14
Page breaking isn't currently an issue with the current templates, but it is when you try to add a box of some kind around the code. I'm curious to try integrating some of sphinx's work into my work over at https://github.com/t-makaro/nb_pdf_template. You can see my current work [in the image above](https://github.com/jupyter/nbconvert/issues/323#issuecomment-417827568). It currently only uses ```\usepackage[breakable]{tcolorbox}```, and ```\usepackage{minted}```, but minted needs a shell escape. With the work done over at sphinx, we could remove the need for minted.

I'll take another crack at adding the work done by sphinx into my project, which I'd absolutely love to contribute back here when I'm done.

This issue is tenchnically only about wrapping output, but I think we can solve both input and output.

**Comment by t-makaro** [comment] 2019-04-25 00:25
I don't have the power to close this, but this was fixed in #992. @MSeal

**Closed** 2019-04-25 02:12 UTC
