### ISSUE TITLE
Retina images lose their width information when converted to .rst

### ISSUE THREAD

**Issue by mscuthbert** [jupyter/nbconvert#589] opened 2017-05-16 01:22 UTC
The display(Image(..., retina=True)) command creates metadata about the image explaining the size that it should be displayed at in the notebook. This information, if present, can be carried into the notebook and converted to rst for use in documenters such as Sphinx. If not present, retina images appear in .rst (and from there to other formats such as HTML) as twice their intended size.

The documentation for music21 is created in Jupyter notebook and Sphinx and the retina generated images are so much clearer than the previous images, but this fix is needed to make it through our workflow of .ipynb -> .rst -> .html

Fixed in #588 -- though this is my first attempt at editing a .tpl file, so I am not sure if I should have also patched the svg+xml as well.

**Comment by willingc** [comment] 2017-05-16 16:23
Hi @mscuthbert, Thanks for the report and the PR. The latest music21 docs look great with the PR rendering.

@mpacer Here's some background as well from the [music 21 mailing list](https://groups.google.com/forum/#!topic/music21list/jNk3vLOviz8). Myke's [music21 project](http://web.mit.edu/music21/doc/about/what.html) is what inspired me to use the notebooks.

**Comment by mscuthbert** [comment] 2017-05-16 19:59
It's made such a huge difference in the music21 documentation! I'll be thrilled when it's generally available.  (See http://web.mit.edu/music21/doc/usersGuide/usersGuide_22_graphing.html )

**Comment by mpacer** [comment] 2017-05-18 16:43
That's awesome!

I'm actually going to use an example of this in something I'm working on regarding figures in the IPython kernel. Thank you for pointing me to it.

Also which aside, don't encourage people to use matplotlib inline anymore — it breaks converted scripts. Instead use matplotlib 2+ and use `matplotlib.pyplot.ion()` which will automatically detect which backend to use if you are in the notebook or otherwise. That means you can write notebooks that convert to .py scripts without manual tweaking.

**Comment by mscuthbert** [comment] 2017-05-24 00:16
Yes!` ion()` and `ioff()` solve a different issue I'm having.  :-)  Thank you!  Solving that will free up time to get to doing this!

**Comment by mpacer** [comment] 2017-05-29 18:29
@mscuthbert So the most recent release should address this issue. Do you still want to work on improving the test to better match your expected behaviour? Or should I close this since it's been dealt with? 

Separately: what were you saying about `svg+xml`, I don't quite follow?

**Comment by mscuthbert** [comment] 2017-06-01 16:35
Hi @mpacer -- I think that we should close this, but I can re-open if I find the time -- I agree that a better test should be written, but I'm having trouble learning the testing system to be able to step through the conversion process in the debugger.

About `svg+xml` -- I do not know if this format can be converted to also use the metadata tag to provide width and height formatting, so I did not add this info to the svg+xml -- if there's a test to see if it converts properly, then I can add it.

Thanks!

**Comment by mpacer** [comment] 2017-06-01 19:31
No worries — metadata wasn't supported directly in declaring an `SVG` DisplayObject before, but that's what https://github.com/ipython/ipython/pull/10614/files is intended to address. 

I don't think you needed to patch anything on svg+xml at least not for now.

**Closed by mpacer** 2017-06-01 19:31 UTC

**Comment by mpacer** [comment] 2017-06-01 19:39
@mscuthbert I'm sorry that you're running into issues i'll change the html exporter and link to that to give you an idea of how to approach it and will describe the debugging process.

**Comment by mscuthbert** [comment] 2017-06-01 19:40
Thank you -- it's surely my ignorance and not a problem of the project's organization.  Thank you so much!

**Comment by mpacer** [comment] 2017-06-01 22:47
@mscuthbert I gave exposition in the initial PR statement. But the key to use pytest to test only the file you are tweaking, use `pdb` to dive into the test context, extract the relevant info (if you need to test something as complicated as a regular expression) and put it in a more powerful editing and testing environment. Then once you have a solution, plug that solution into the test and make sure that it succeeds in the way that you expect.

So for your case, you'll want to do this on the test_rst.py and grab the output, make sure you're only looking at the image block in the resulting text and then check that the attributes are specified in a manner that is valid for rst image width and height specification.

Let me know if there's anything that's unclear.
