### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'argv' 

### ISSUE THREAD

**Issue by tom888888** [jupyter/nbconvert#891] opened 2018-10-01 08:08 UTC
When I used run_jnb , the error is occured
 ```
AttributeError: 'NoneType' object has no attribute 'argv'
```
the dependency of nbconvert is 5.4.0

And I try to change the nbconvert version to 5.3.1 , the error isn't occured

And the other dependencies of jupyter notebook and run_jnb that I installed the latest version

Could you please advice how to solve out this error
Thank you

**Comment by mgeier** [comment] 2018-12-04 09:44
I guess this is a duplicate of #878.

**Comment by t-makaro** [comment] 2019-08-02 18:20
Closing as a duplicate of #878

**Closed by t-makaro** 2019-08-02 18:20 UTC
