### ISSUE TITLE
Config option `exclude_input` not recognized by `HTMLExporter`.

### ISSUE THREAD

**Issue by YoavEtzioni** [jupyter/nbconvert#833] opened 2018-07-02 06:16 UTC
Hi

In one of my computer (windows) I am routinly using the command:

jupyter-nbconvert -to html --TemplateExporter.exclude_input=True --execute --output output_html notebook.ipynb

However when trying the same command on another (linux) I get the header massage.:

Config optionexclude_inputnot recognized byHTMLExporter.

I did update nbconvert , so it does not seem to be the reason. Can anyone suggest what am I missing? Or another procedure for printing notebook to html?

**Comment by t-makaro** [comment] 2019-08-02 02:14
I believe this was fixed in 5.4.0 by #734. Closing as I cannot reproduce this on master. Please comment asking to reopen if this is still an issue.

**Closed by t-makaro** 2019-08-02 02:14 UTC
