### ISSUE TITLE
Converting to slides

### ISSUE THREAD

**Issue by achapkowski** [jupyter/nbconvert#546] opened 2017-03-10 13:05 UTC
Hello,

When I run nbconvert with or without commands, I get the following message:

```
jupyter-nbconvert.exe
failed to create process.```


I've tried reinstalling and I still get the same issue.

**Comment by takluyver** [comment] 2017-03-15 12:19
Weird. Can you send a screenshot to show exactly how you're invoking it? Do other Jupyter commands run (e.g. `jupyter notebook`)? How are you (re)installing it?

**Comment by damianavila** [comment] 2017-05-31 22:08
> Weird. Can you send a screenshot to show exactly how you're invoking it? Do other Jupyter commands run (e.g. jupyter notebook)? How are you (re)installing it?

ping @achapkowski, can you provide the requested info?

**Comment by damianavila** [comment] 2017-06-07 13:35
Will close this one since we did not have any updates in months.
@achapkowski feel free to re-open if you still see this and have the information requested.

**Comment by jwood803** [comment] 2017-08-24 12:06
I seem to be seeing this same thing:
```
$ jupyter nbconvert
failed to create process.
```

I can run `jupyter notebook` perfectly and notebooks run with no issues. Is there any other info that's needed?

**Comment by takluyver** [comment] 2017-08-24 12:10
The `jupyter` command runs subcommands by looking for an executable called (for instance) `jupyter-nbconvert`. Do you see the same error running it with the hyphen?

**Comment by jwood803** [comment] 2017-08-24 12:21
Yep, same error:
```
$ jupyter-nbconvert
failed to create process.
```

I did a `conda list` to see if it was there and I don't see it listed.
![image](https://user-images.githubusercontent.com/1578160/29666157-213644d4-88a5-11e7-87d3-65315049752a.png)

Does it need to be installed separately?

**Comment by takluyver** [comment] 2017-08-24 12:51
It is a separate package, but I'd expect a different error if it wasn't there. The conda package is `nbconvert`.

If that's present, what does `which jupyter-nbconvert` give you?

**Comment by jwood803** [comment] 2017-08-24 13:05
Looks like it's able to find it with the `which` command.
```
$ which jupyter-nbconvert
/c/Program Files/Anaconda3/Scripts/jupyter-nbconvert
```

**Comment by takluyver** [comment] 2017-08-24 13:13
Oh, hang on, is that a Windows executable used in something like WSL? If you're using the Windows 10 Linux system, you need to install a Linux version of Python inside that.

**Comment by jwood803** [comment] 2017-08-24 13:34
I was just using bash from Cmder. In PowerShell, I get this:
```
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     jupyter-nbconvert.exe                              0.0.0.0    C:\Program Files\Anaconda3\Scripts\jupyter-nbconvert.exe
```

Interesting that version is all zeros...

**Comment by takluyver** [comment] 2017-08-24 13:36
Windows has some mechanism for embedding a version number header into exe files, which Python programs don't generally use.

Does running nbconvert from powershell work?

**Comment by jwood803** [comment] 2017-08-24 13:41
Unfortunately, it gives the same error. :(

________________________________

**Comment by takluyver** [comment] 2017-08-24 13:44
Try uninstalling nbconvert with conda and installing it again?

**Comment by jwood803** [comment] 2017-08-24 14:28
Uninstalled `nbconvert` and even `notebook`, but no luck.

I can get around this by just using the "Download as" option in the UI. 😃

**Comment by takluyver** [comment] 2017-08-24 14:39
Weird. It's possible that conda has cached a corrupt copy of the file which comes back even when you remove it. Or there could be an issue with the conda package. Try uninstalling it with conda and then installing it using pip.

**Comment by erihanse** [comment] 2017-09-07 11:27
Same problem here. Anaconda navigator says version 5.2.1. Windows 10. Running the script natively and not in WSL. 

```
PS C:\WINDOWS\system32> jupyter-nbconvert.exe
failed to create process.
```

**Comment by Jeff-Winchell** [comment] 2017-12-09 02:13
Hey, if you are going to claim to support Windows, then do some basic testing assuming a Windows mindset.

I was able to run jupyter nbconvert on the Windows command line by doing this

python "long path to the files that includes characters LINUX doesn't like\jupyter-nbconvert-script.py" whateverparameters

then you should get it to work.

Pay attention to spaces, they are ALL OVER windows and forcing your product to only run on systems that don't include spaces in the filename/file path is dumb/arrogant (pick your adjective).

**Comment by fperez** [comment] 2017-12-09 04:29
@Jeff-Winchell, we do test on Windows, and do our best to ensure that all the Jupyter tools work as well as possible on Windows. Overall on the team we have more Linux/macOS expertise, but we actively try to provide a robust Windows experience, within our abilities.

In this case, the problem is that we're not 100% sure what is going on here.  On  a currently up-to-date version of Windows 10 with an updated Anaconda install, I get the following:

![image](https://user-images.githubusercontent.com/57394/33792477-c4c071f2-dc55-11e7-8710-2d2bb4dbc285.png)

This test was conducted with both a conda instlalled into a path with spaces in it, *and* with a notebook also living in a directory with spaces in it.  We use Python's subprocess machinery to ensure that paths with spaces in them work as well as possible.

Evidently the issue that @erihanse and others are reporting is real, but we don't understand its root cause yet. If we can better understand the installation conditions that are leading to them seeing this problem, we'll be happy to fix it, if it's on the nbconvert or jupyter wrapper side.  Until then, given that in our tests it's working fine, we can't make much progress.

However, language like this:

> Pay attention to spaces, they are ALL OVER windows and forcing your product to only run on systems that don't include spaces in the filename/file path is dumb/arrogant (pick your adjective).

is both a very unproductive way to engage a developer team,  and completely unwelcome in our repositories and community.  

I recommend that you read [Bret Cannon's excellent post](https://nothingbutsnark.silvrback.com/why-i-took-october-off-from-oss-volunteering), on why this harms the long-term health of open source communities.

**Comment by Jeff-Winchell** [comment] 2017-12-09 05:07
As Ward Cunningham has told me, do the simplest thing that could possibly
work. I don't think that's the case here (or in the vast majority of
software I see).

My guess is by relying on all sorts of complex things, finding the cause of
this bug will not be easy.

**Comment by Jeff-Winchell** [comment] 2017-12-09 05:11
Well, at least you have the workaround I provided so people who also
experience this bug can make use of the various other switches you have
that aren't available when you just download a notebook from within jupyter.

**Comment by ivanov** [comment] 2017-12-09 05:33
> As Ward Cunningham has told me, do the simplest thing that could possibly work. I don't think that's the case here (or in the vast majority of software I see).

As Kurt Vonnegut wrote: "_Hello, babies. Welcome to Earth. It's hot in the summer and cold in the winter. It's round and wet and crowded. At the outside, babies, you've got a hundred years here. There's only one rule that I know of, babies - God damn it, you've got to be kind."_ 

and I don't think that's the case with your behavior here.

> Well, at least you have the workaround I provided so people who also experience this bug can make use of the various other switches you have that aren't available when you just download a notebook from within jupyter.

I disagree. If the workarounds provided come at the cost of a hostile environment (your "dumb/arrogant" remark, for example) , they are not worth the price.

**Comment by erihanse** [comment] 2017-12-09 05:39
Your behaviour Jeff doesn't really adhere to the philosophy of open source. Maybe try a more neutral/supportive approach in the future, we all want the same thing here.

**Comment by Jeff-Winchell** [comment] 2017-12-09 06:15
I find it ironic when people criticize people for critizing people.

On Sat, Dec 9, 2017 at 12:39 AM, Erik Aaron Hansen <notifications@github.com

**Comment by erihanse** [comment] 2017-12-09 06:22
Well there's constructive criticism and there's inconstructive. You will achieve better results by following a few easy social norms. The same norms that apply outside the open source community for that matter. You can do it, I know you can :) 

Why is this marked as closed by the way? Is it fixed, do I need to update?

**Comment by takluyver** [comment] 2017-12-09 10:51
It was closed some time ago because the original reporter didn't provide further info,  and at the time it looked like it was a one-off. We should have reopened it when it was clear that other people were experiencing the error, but the notifications we get for comments are the same regardless of its state, so I probably overlooked that it had been closed.

**Comment by takluyver** [comment] 2017-12-09 10:56
If you're using nbconvert installed by conda, can you try uninstalling it with conda and installing it again with pip?

**Comment by blink1073** [comment] 2017-12-09 11:13
I was able to reproduce the `failed to create process` bug using `nbconvert 5.2.1` from the default `conda` channel.  However, all of the following combinations worked: 

```bash
conda install -c defaults nbconvert=5.3.1
conda install -c conda-forge nbconvert=5.2.1
conda install -c conda-forge nbconvert=5.3.1
```

**Comment by blink1073** [comment] 2017-12-09 11:15
Note that moving forward, the default conda packages are based on the conda-forge recipes if possible.

**Comment by blink1073** [comment] 2017-12-09 11:22
@Jeff-Winchell, please be civil and refrain from calling the folks that offer you the sweat of their labor for free dumb and arrogant.  Open source only works because of people.

**Comment by jwood803** [comment] 2017-12-09 14:43
It looks like reinstalling `nbconvert` worked for me like @blink1073 mentioned above.

Appreciate all the help @takluyver! Apologies I didn't follow up back in August.

**Comment by fperez** [comment] 2017-12-09 22:08
Oddly enough, even with

```
conda install -c defaults nbconvert=5.2.1
```

I can't replicate the problem, the conversion runs fine for me.

But it appears clear that this was an issue with some combination of conda recipes and perhaps other packages, which as best we can tell, is solved by updating. Also, since the bug doesn't appear to be in nbconvert itself, let's close this.   We can reopen or create a new issue if anyone sees the process creation problem again.

**Closed by fperez** 2017-12-09 22:08 UTC
Labels: slides

**Comment by Jeff-Winchell** [comment] 2017-12-09 22:16
I run the anaconda distribution of python that comes bundled with SQL Server 2017. Updating python to some version not officially supported by Microsoft SQL Server 2017 is not tested by Microsoft and therefore not recommended.

**Comment by blink1073** [comment] 2017-12-09 23:25
@Jeff-Winchell, I'd recommend opening an issue on https://github.com/ContinuumIO/anaconda-issues.

**Comment by damianavila** [comment] 2018-01-21 20:33
Changed title to `Conversion fails on win` because this was not related to the slides and describes better the discussion.
