### ISSUE TITLE
incompatibility with nb_conda_kernels

### ISSUE THREAD

**Issue by scottdraves** [jupyter/nbconvert#770] opened 2018-02-26 19:40 UTC
If you use https://github.com/Anaconda-Platform/nb_conda_kernels and save a notebook, and then run that notebook with `nbconvert --execute` the kernel will be not found because the environment  name is encoded into the kernel name, but nbconvert doesn't know this.

**Comment by scottdraves** [comment] 2018-02-26 19:40
https://github.com/Anaconda-Platform/nb_conda_kernels/issues/77

**Comment by mpacer** [comment] 2018-02-26 21:33
I think this is a duplicate of a previous issue, please check out https://github.com/jupyter/nbconvert/issues/515. 

If you think this is not a duplicate, please comment and we will reopen.

**Closed by mpacer** 2018-02-26 21:33 UTC
