### ISSUE TITLE
Conversion of notebook to latex and pdf renders markdown font monospaced after display of sympy symbol

### ISSUE THREAD

**Issue by fangohr** [jupyter/nbconvert#1223] opened 2020-03-28 07:50 UTC
# Description

The attached notebook `sympy.ipynb` demonstrates that the rendering of the
markdown text in pdf files created with `jupyter-nbconvert --to pdf sympy.ipynb`
is always as a monospaced font, _after_ a symbolic variable from sympy has been
displayed as a value in the notebook. (In LaTeX terms, the markdown shows up in
the tt-font.)

In the attached example, the problem starts to occur after cell `[3]`. It
remains monospaced for subsequent output cells. Note that this is also true for
the markdown after cell `[6]`.

Attached is a notebook file (original filename for the description here is
`sympy.ipynb`) which produces the pdf file, which is shown in the screen shot.

![screenshot](https://user-images.githubusercontent.com/4489119/77818216-fe4a1d80-70d0-11ea-9b26-1d3c35ed6d68.png)

**How to reproduce**
- start from new python 3 (conda) environment
- pip install nbconvert 
- jupyter-nbconvert --to pdf sympy.ipynb

The resulting `sympy.pdf` shows the issues as described above (see ``screenshot.png`)

**Nbconvert version:**
```$ jupyter-nbconvert --version
5.6.1
```
(installed via pip on 28 March 2020

**Additional observation, LaTeX file**

When generating a LaTeX file (`jupyter-nbconvert --to latex sympy.ipynb`), and
then creating a pdf from the latex file (`pdflatex sympy.tex`), then the output
shows the same issue. 

I also attach the `sympy.tex` file, so people can look into this. Here are two sections of the file:

1. Snippet with Correctly rendered markdown output:
   ```
               \begin{tcolorbox}[breakable, size=fbox, boxrule=.5pt, pad at break*=1mm, opacityfill=0]
   \prompt{Out}{outcolor}{2}{\boxspacing}
   \begin{Verbatim}[commandchars=\\\{\}]
   sympy.core.symbol.Symbol
   \end{Verbatim}
   \end{tcolorbox}
           
       Markdown is rendered normally.
   
       Once we display a symbolic variable, \ldots{}
   
   ```

2. Snippet with incorrectly rendered markdown output:
   ```
       \begin{tcolorbox}[breakable, size=fbox, boxrule=1pt, pad at break*=1mm,colback=cellbackground, colframe=cellborder]
   \prompt{In}{incolor}{3}{\boxspacing}
   \begin{Verbatim}[commandchars=\\\{\}]
   \PY{n}{x}
   \end{Verbatim}
   \end{tcolorbox}
    
               
   \prompt{Out}{outcolor}{3}{}
       
       $\displaystyle x$
   
       
   
       \ldots{} subsequent markdown is rendered as monospaced font.
   
   
   ```

Versions of other software:

```
$ pdflatex --version 
pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019)
kpathsea version 6.3.1
Copyright 2019 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.36; using libpng 1.6.36
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.01

$ pandoc --version 
pandoc 2.2.3.2
Compiled with pandoc-types 1.17.5.1, texmath 0.11.0.1, skylighting 0.7.2
Default user data directory: /Users/fangohr/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

$ python --version
Python 3.8.2
```

[sympy.ipynb.txt](https://github.com/jupyter/nbconvert/files/4396788/sympy.ipynb.txt)
[sympy.tex.txt](https://github.com/jupyter/nbconvert/files/4396789/sympy.tex.txt)

**Comment by mgeier** [comment] 2020-03-28 08:48
This looks like #1151 which has been fixed in #1153 but there hasn't been a new `nbconvert` release since then.

**Comment by MSeal** [comment] 2020-03-28 19:06
Yes sorry we haven't been getting 6.0 rolling well. I'm planning on pushing that release more to get all the changes pending out to users. Expect a new alpha release in the next week.

**Comment by fangohr** [comment] 2020-03-30 10:07
Thanks @mgeier - I should have noticed the existing ticket, sorry.

@MSeal - a new release would be great news :)

Many thanks all for pushing this nice project forward.

**Comment by t-makaro** [comment] 2020-04-04 04:39
I just confirmed that this is fixed currently in master. Closing.

**Closed by t-makaro** 2020-04-04 04:39 UTC

**Comment by MSeal** [comment] 2020-04-04 05:32
@fangohr 6.0.0a1 pre-release should have everything in master -- we're got over some of the larger items for 6.0 non-alpha release so hopefully a full release soon!
