### ISSUE TITLE
The LaTeX export use unexpected verbatim font

### ISSUE THREAD

**Issue by mbaudin47** [jupyter/nbconvert#1197] opened 2020-02-23 10:13 UTC
Consider the following notebook.

[bug-format-ttt-latex.ipynb.txt](https://github.com/jupyter/nbconvert/files/4240798/bug-format-ttt-latex.ipynb.txt)

I converted into LaTeX then built PDF using:
```
$ jupyter nbconvert --to latex bug-format-ttt-latex.ipynb
$ pdflatex bug-format-ttt-latex.tex
```

This produces the following PDF:

[bug-format-ttt-latex.pdf](https://github.com/jupyter/nbconvert/files/4240801/bug-format-ttt-latex.pdf)

Notice that the text "On observe après." does not have the correct font: it has verbatim-style instead of the regular text font. 

![Screenshot from 2020-02-23 11-04-12](https://user-images.githubusercontent.com/31351465/75110293-c57bdc00-562c-11ea-917f-fb45adafce01.png)

In order to find the bug, I exported the document into LaTeX:

[bug-format-ttt-latex.zip](https://github.com/jupyter/nbconvert/files/4240824/bug-format-ttt-latex.zip)

But I could not find where the bug is. 

**Nbconvert version:**
```
$ jupyter nbconvert --version
5.6.1
```

**Comment by t-makaro** [comment] 2020-02-23 19:51
Closing as duplicate of #1151. A release of nbconvert will be needed to get the fix.

**Closed by t-makaro** 2020-02-23 19:51 UTC
Labels: duplicate, format:LaTeX
