### ISSUE TITLE
Conversion Error message does not have enough context

### ISSUE THREAD

**Issue by blink1073** [jupyter/nbconvert#613] opened 2017-06-28 12:34 UTC
Migrated from https://github.com/jupyterlab/jupyterlab/issues/2541.

@marberi reports:

I managed to solved this issues by installing the right packages. The error
message was a bit cryptic, since it failed for an earlier problem than what
it could seem in the error message. It seems like the code should include
a test of what is installed to catch this problem.

When trying to run
http://localhost:8888/nbconvert/pdf/Untitled.ipynb?download=true

it displays the error message [1]. By looking in the code and copying
the temporary latex directory, I traced the problem back to:

eriksen@bever:~/tmp/tmp/tmpK586Zu$ mktexpk --mfmode / --bdpi 600 --mag 1+0/600 --dpi 600 ectt1095
mktexpk: don't know how to create bitmap font for ectt1095.
mktexpk: perhaps ectt1095 is missing from the map file.

which could be solved by:
sudo apt install texlive-full

[1]
nbconvert failed: PDF creating failed, captured latex output:
This is BibTeX, Version 0.99d (TeX Live 2016)
The top-level auxiliary file: notebook.aux
I found no \citation commands---while reading file notebook.aux
I found no \bibdata command---while reading file notebook.aux
I found no \bibstyle command---while reading file notebook.aux
(There were 3 error messages)

**Comment by mpacer** [comment] 2017-06-28 14:19
This is a long standing challenge. We can't use texlive-full on travis but we also can't seem to get it to reproducibly create errors that sometimes arise based on people's idiosyncratic TeX library distributions. If we direct people to use TeXlive full, then it becomes really hard to trust travis for anything test related. See any of the PRs on font support to get an idea of this problem & its intractability.

The other approach (catching errors and interpreting them from LaTeX) is not something I would wish on anyone. 

So I'm closing this because our general policy for TeX issues has been that while unfortunate solving TeX dependency problems is simply outside our purview.

If anyone has a suggestion about a different approach I'm open minded and we should reopen the issue.

**Closed by mpacer** 2017-06-28 14:19 UTC
