### ISSUE TITLE
Output tex "content" and "header-stuff" in separate files?

### ISSUE THREAD

**Issue by PanosFirmpas** [jupyter/nbconvert#943] opened 2019-01-15 16:05 UTC
I'm looking to include a number of notebooks inside a larger latex project (my thesis).     
       
Right now, I convert them to tex with a semi-custom .tplx template, pdflatex those and finally     
include the pdfs in the larger latex file with \includepdf[]{notebookXX.pdf}     
      
It works decently well (They even properly get page numbers), but isn't it very redundant?     
As far as I can tell, all of my notebook tex files contain the same stuff at the "header" section.      
       
If I could have them output separately, I could include the header part ONCE in my large latex project and then very simply \input{} the notebookXX.tex chunks in the appropriate parts of my thesis.     
       
Then I could also simply include global citations from my thesis in my notebooks.. It feels like a very intuitive and "organic" solution but I might be missing something..?

I had a look in the repo but I got completely lost and couldn't identify where this part of the magic happens (I was hoping for a quick hack solution), so could someone maybe point me to the right direction or offer thoughts/advice?

**Comment by mgeier** [comment] 2019-01-17 18:50
I'm currently trying to do a very similar thing!

> If I could have them output separately, I could include the header part ONCE in my large latex project and then very simply \input{} the notebookXX.tex chunks in the appropriate parts of my thesis.

This sounds like the way to go. I would just remove the "header-stuff" from my custom template and just copy the header manually to the "parent" LaTeX file.

I didn't try this with `nbconvert`, but with [nbsphinx](https://nbsphinx.readthedocs.io/) (full disclosure: I'm its author). IMHO the code cells look much better in its LaTeX output, see e.g. https://media.readthedocs.org/pdf/nbsphinx/latest/nbsphinx.pdf#section.4.

I've created a Sphinx LaTeX template `_templates/latex.tex_t` with only this content:

    <%= body %>

... and used `\input{}` to include the result in my thesis.

Copying the "header-stuff" manually is a bit annoying, but I don't know a better way to do it.

**Comment by t-makaro** [comment] 2019-08-07 00:38
Closing as duplicate of #239.

**Closed by t-makaro** 2019-08-07 00:38 UTC
Labels: format:LaTeX
