### ISSUE TITLE
Timeout running notebook with numba-jitted function

### ISSUE THREAD

**Issue by tritemio** [jupyter/nbconvert#632] opened 2017-07-26 05:41 UTC
Hi,

I have [a notebook](https://github.com/tritemio/pycorrelate/blob/master/notebooks/pycorrelate-examples.ipynb) containing a function decorated with `numba.jit` that runs under 1s (`pycorrelate.correlate`). Without numba the function takes > 100s. When I run the notebook from the Notebook App there is no problem. But when I try to run it through nbconvert the function is somehow not jitted and the execution times out. If I run the notebook on a smaller dataset the execution completes correctly.

Any idea what is going on?

I initially [reported this](https://github.com/spatialaudio/nbsphinx/issues/116) to `nbsphinx`  issue because I found the issue trying to include the notebook in the documentation.

**Comment by takluyver** [comment] 2017-07-26 08:35
That's weird. Ideas:

- Does numba have some sort of cache? Does it run the function once un-jitted before trying to jit it? I know tracing JITs work like this - run the slow version of code at first, and then JIT pieces which are called repeatedly. I didn't think numba worked that way, but it may have got more advanced since I looked into it.
- Is it possible that it's running in a different Python installation when you run it with nbconvert? Maybe it's using a different version of numba, or the conditions mean numba can't jit it for some reason.

**Comment by tritemio** [comment] 2017-07-26 16:55
@takluyver, thanks for bringing up the environment issue. I turns out I was using nbconvert in a different environment than when using the notebook app. Both environments are very similar and have the same numba version (0.34.0) but the one I was using with nbconvert has this issue with numba. I either cases I'm using the `numba.jit(nopython=True)` so the function should always get jitted, but it is (silently) not jitted in one of the two environments.

**Comment by takluyver** [comment] 2017-07-26 16:57
Bizarre! I'm glad you've got a clue about the problem. I'll close this issue since it's not a bug in nbconvert.

**Closed by takluyver** 2017-07-26 16:57 UTC
