### ISSUE TITLE
RawNbconvert cell not working for slides

### ISSUE THREAD

**Issue by basnijholt** [jupyter/nbconvert#282] opened 2016-04-05 20:22 UTC
Putting some `css` in a raw cell and converting it too slides doesn't respect the `css`.

See [this gist](https://gist.github.com/basnijholt/ca3f0b9baa552340f786ade5fcc0aeb5) and convert with:
`jupyter nbconvert nbconvert-test.ipynb --to slides --reveal-prefix=https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.1.0`

This `css` is supposed to (among other things) hide the cells:

``` html
<style>
.input, .output_prompt {display:none !important;}
div.prompt {display: none}
.container { width:80% !important;}
.slides{width: 80% !important; height: 80% !important;}
div.text_cell_render{overflow-y:hidden}
a.anchor-link{display:none}
html{overflow-y:hidden} 
</style>
```

I checked the output with `nbconvert=4.0.0` and old reveal, which works fine.

**Comment by damianavila** [comment] 2016-04-05 23:50
Thanks @basnijholt... I will take a look tomorrow (little bit late here :wink:)

**Comment by TKGgunter** [comment] 2016-07-14 07:55
Has a fix been found for this bug

**Comment by mpacer** [comment] 2017-04-04 21:47
Is this bug still active?

**Comment by damianavila** [comment] 2017-04-06 22:17
I need to check it. I will report back when it is done.

**Comment by damianavila** [comment] 2017-05-31 22:38
The problem is that you `skipped` the styling cell, which means it will not be added into the final foo.slides.html.
You can put the styling in the last slide, or use the type `notes`. Or alternative use a local `custom.css` along side with you presentation.
If it was working before, I don't know how, but it should not be working from a cell labeled as `Skip`.
Going to close this but feel free to comment or reopen it if it is necessary.

**Closed by damianavila** 2017-05-31 22:38 UTC
Labels: slides
