### ISSUE TITLE
Make HTML export responsive/mobile friendly

### ISSUE THREAD

**Issue by hanzhihua72** [jupyter/nbconvert#1094] opened 2019-09-03 15:50 UTC
https://github.com/jupyterlab/jupyterlab/issues/3275

The advantage of exporting as HTML is that any widgets made using jupyter notebook/lab is are interactive. Currently exporting code as HTML is not mobile-friendly. 

One application would be in scientific presentations. Many scientists make plots that are interactive instead of static. You could imagine all an audience member has to do to play with the plots is simply view the HTML file in their browser. As you might have guessed, this doesn't look very nice on mobile. This might not matter for lectures where more people have laptops ready, but for poster sessions, the only device people have on hands are usually their phones. 

When exporting as HTML, add support for mobile. In general, make HTML exports responsive to any browser.

Currently, HTML exports are designed only for desktop browsers. Others have suggested to make Jupyter Notebook/Lab itself mobile-friendly which would be nice but might be difficult to implement.

**Comment by t-makaro** [comment] 2019-09-03 17:29
Closing as duplicate of #599.

**Closed by t-makaro** 2019-09-03 17:29 UTC
