### ISSUE TITLE
Reveal odd latex formatting

### ISSUE THREAD

**Issue by akhmerov** [jupyter/nbconvert#43] opened 2015-06-17 19:02 UTC
This is going to be super-fun to debug:

`* $A \parallel B_{CD}$`

renders as

![reveal_bug](https://cloud.githubusercontent.com/assets/2069677/8215956/c7ddaa30-1533-11e5-9c80-8b16f454cd57.png)

in `--to slides` (a line break is inserted or so). It renders correctly in `--to html`. Removing any one of `*`, `\parallel`, or replacing `{CD}` with `{C}` fixes the rendering.

A workaround is to split a single math environment into several: `$A$ $\parallel$ $B_{CD}$`. Not sure what to do with `$$ $$`.

**Comment by takluyver** [comment] 2015-06-17 19:06
@damianavila , another slides related thing. Maybe some mathjax CSS (does mathjax use CSS?) is clashing with reveal stuff.

**Comment by damianavila** [comment] 2015-06-17 20:01
Interesting...  it could be some clashing, I have to investigate (IIRC, reveal have a mathjax plugin, so maybe they are using some other configuration we can research into if we don't figured out at first sight what is the issue here).

btw @takluyver can you assign these issues to me, so I can filter them easily... or add me to the repo and I assign the slides-related thing to myself... thx

**Comment by akhmerov** [comment] 2015-06-17 21:28
It might help to know that whatever it is, it doesn't happen in RISE.

**Comment by damianavila** [comment] 2015-06-17 22:13
Thanks for the RISE note... then seems to be nbconvert related... we'll need to figured out.

**Comment by takluyver** [comment] 2015-06-17 22:19
@damianavila I've invited you to collaborate on this repo so we can assign issues to you. As you've probably already seen, we all try to collaborate via pull requests rather than pushing directly. You'll be able to review and merge other people's pull requests, but if you're in any doubt about a PR, feel free to ask for another pair of eyes on it. :-)

**Comment by takluyver** [comment] 2015-06-17 22:20
I also made a slides tag to group issues related to the slides output.

**Comment by damianavila** [comment] 2015-06-17 22:25
Thanks.
The slides tag is very useful... and about the practices, I practice (and encourage to others) the same ones in several of the open source project I am involved with :wink:

**Comment by damianavila** [comment] 2015-07-20 12:34
@akhmerov, I can not reproduce the issue...

I tried `* $A \parallel B_{CD}$` and it renders OK, without the final `$` it does not render even in the notebook, so I guess it is the correct expression (I don't know too much about latex).

I tried with several versions of mistune (there was an issue recently with 0.6) but even in that case I could not reproduce the issue... do you have a notebook where you see it? Cheers.

**Comment by akhmerov** [comment] 2015-07-20 14:13
Here:

http://nbviewer.ipython.org/format/slides/url/antonakhmerov.org/misc/revealbug.ipynb#/

PS apologies for missing `$`, it's a typo (now fixed).

**Comment by damianavila** [comment] 2015-07-20 19:47
@bollwyvl, ideas? I don't think of anything affecting directly nbviewer without affecting nbconvert as well... maybe something in the slides.less file?? or some other css setting in nbviewer?

**Comment by basnijholt** [comment] 2015-09-15 18:10
I'm experiencing similar issues, any updates on this?

**Comment by michaelpacer** [comment] 2016-08-18 01:33
@akhmerov Is this still an issue for you or has it been fixed? Did #104 take care of it?

**Comment by akhmerov** [comment] 2016-08-18 06:56
I have just confirmed it is still there in nbconvert 4.2.0.

**Comment by damianavila** [comment] 2017-05-31 20:28
I just tested with nbconvert 5.2.1 and both `html` and `slides` options render the equation correctly.
So, closing this one now.

**Closed by damianavila** 2017-05-31 20:28 UTC
Labels: slides

**Comment by akhmerov** [comment] 2017-05-31 20:42
Indeed, also nbviewer does everything correctly now.
