### ISSUE TITLE
NbConvertApp ignores raises-exception metadata

### ISSUE THREAD

**Issue by rlabbe** [jupyter/nbconvert#838] opened 2018-07-14 17:16 UTC
In the notebook you can add the tag 'raises-exception' to a cell to denote that it is expected to raise an exception. With this tag, if you run all cells, cells after the cell that raises the exception will be run.

In contrast, if you run that notebook from the command line with

     jupyter nbconvert --inplace --execute a.ipynb

the exception will be raised and not handled by nbconvert. Instead, it terminates execution and does not write anything to the notebook.

I argue the behavior should be the same as in the notebook - the cell output should contain the exception traceback, subsequent cells should still be executed and the result should be saved to the output file.

I'm aware of --allow-errors, but that is not the behavior I want. I don't want to suppress *all* errors, since in general an exception is a true bug that I don't want to hide from myself. I deliberately use the tag only on cells which are expected to raise the error.

**Comment by takluyver** [comment] 2018-07-14 18:21
@mpacer did this in #684, but we haven't made a release since then.

**Comment by t-makaro** [comment] 2019-08-02 03:47
I just confirmed that this feature does work in the latest release. Closing.

**Closed by t-makaro** 2019-08-02 03:47 UTC
